### PR TITLE
Py.test collection errors (closes #1919)

### LINKED ISSUE #1919: running tests locally when not all extras are installed causes pytest collection error
I've been running into this while testing Travis, but the setup to recreate is

- clone repo
- new virtualenv
- source virutalenv
- make prepare
- make develop
- make test_offline

And the pytest log looks something like

```
All docker related tests will be skipped.
TOIL_SKIP_DOCKER=True \
		python2.7 -m pytest -vv --timeout=530 src
============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-2.8.3, py-1.4.34, pluggy-0.3.1 -- /home/travis/virtualenv/python2.7.13/bin/python2.7
cachedir: .cache
rootdir: /home/travis/build/jessebrennan/toil, inifile: setup.cfg
plugins: timeout-1.2.0
timeout: 530.0s method: signal
collecting ... collected 326 items / 12 errors
src/toil/__init__.py::toil.physicalMemory PASSED
src/toil/common.py::toil.common.parseSetEnv PASSED
src/toil/fileStore.py::toil.fileStore.DeferredFunction PASSED
src/toil/job.py::toil.job.JobLikeObject._parseResource PASSED
src/toil/realtimeLogger.py::toil.realtimeLogger.RealtimeLogger PASSED
```
.
.
.
```
src/toil/test/utils/utilsTest.py::UtilsTest::testUtilsSort PASSED
src/toil/test/utils/utilsTest.py::UtilsTest::testUtilsStatsSort PASSED
==================================== ERRORS ====================================
____________ ERROR collecting src/toil/jobStores/googleJobStore.py _____________
src/toil/jobStores/googleJobStore.py:24: in <module>
    import boto
E   ImportError: No module named boto
____________ ERROR collecting src/toil/jobStores/googleJobStore.py _____________
src/toil/jobStores/googleJobStore.py:24: in <module>
    import boto
E   ImportError: No module named boto
____________ ERROR collecting src/toil/provisioners/aws/__init__.py ____________
src/toil/provisioners/aws/__init__.py:19: in <module>
    from cgcloud.lib.util import std_dev, mean
E   ImportError: No module named cgcloud.lib.util
____________ ERROR collecting src/toil/provisioners/aws/__init__.py ____________
src/toil/provisioners/aws/__init__.py:19: in <module>
    from cgcloud.lib.util import std_dev, mean
E   ImportError: No module named cgcloud.lib.util
_________ ERROR collecting src/toil/provisioners/aws/awsProvisioner.py _________
../../../virtualenv/python2.7.13/lib/python2.7/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
src/toil/provisioners/aws/__init__.py:19: in <module>
    from cgcloud.lib.util import std_dev, mean
E   ImportError: No module named cgcloud.lib.util
_________ ERROR collecting src/toil/provisioners/aws/awsProvisioner.py _________
../../../virtualenv/python2.7.13/lib/python2.7/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
src/toil/provisioners/aws/__init__.py:19: in <module>
    from cgcloud.lib.util import std_dev, mean
E   ImportError: No module named cgcloud.lib.util
___________ ERROR collecting src/toil/test/jobStores/jobStoreTest.py ___________
src/toil/test/jobStores/jobStoreTest.py:59: in <module>
    from toil.jobStores.aws.utils import region_to_bucket_location
src/toil/jobStores/aws/utils.py:38: in <module>
    import boto
E   ImportError: No module named boto
___________ ERROR collecting src/toil/test/jobStores/jobStoreTest.py ___________
src/toil/test/jobStores/jobStoreTest.py:59: in <module>
    from toil.jobStores.aws.utils import region_to_bucket_location
src/toil/jobStores/aws/utils.py:38: in <module>
    import boto
E   ImportError: No module named boto
____ ERROR collecting src/toil/test/provisioners/aws/awsProvisionerTest.py _____
src/toil/test/provisioners/aws/awsProvisionerTest.py:27: in <module>
    from boto.ec2.blockdevicemapping import BlockDeviceType
E   ImportError: No module named boto.ec2.blockdevicemapping
____ ERROR collecting src/toil/test/provisioners/aws/awsProvisionerTest.py _____
src/toil/test/provisioners/aws/awsProvisionerTest.py:27: in <module>
    from boto.ec2.blockdevicemapping import BlockDeviceType
E   ImportError: No module named boto.ec2.blockdevicemapping
_________ ERROR collecting src/toil/test/src/multipartTransferTest.py __________
src/toil/test/src/multipartTransferTest.py:23: in <module>
    import boto
E   ImportError: No module named boto
_________ ERROR collecting src/toil/test/src/multipartTransferTest.py __________
src/toil/test/src/multipartTransferTest.py:23: in <module>
    import boto
E   ImportError: No module named boto
=== 137 passed, 189 skipped, 2 pytest-warnings, 12 error in 1794.60 seconds ====
make: *** [test_offline] Error 1
The command "make test_offline" exited with 2.
```

### PR DESCRIPTION
**Pull request by ejacox**
I tried some of the work arounds that @jessebrennan was suggesting. They were getting complicated quickly. The only needed extra is aws to avoid the errors. This PR just makes a note of that. 

Fixed some bad links in the docs, too.

### CODE REVIEW

**Comment by ejacox** [comment]
Jenkins, skip this test.

**Comment by ejacox** [comment]
@jessebrennan, What do you think of doing it like this? Many of the failures were in embedded tests,  which we could skip for offline test.

**Comment by ejacox** [comment]
Jenkins, test this please.

**Comment by jessebrennan** [comment]
Can you explain what you mean by embedded tests? I've thought of this
before, but I was unsure what would be missed.

**Comment by ejacox** [comment]
Those bits of codes in the comments. Py.test treats them as tests. See parseSetEnv() in common.py for an example.

**Comment by jessebrennan** [comment]
That seems fine to me. Is there anything else that would be skipped?

**Comment by ejacox** [comment]
@jessebrennan Nothing else would be skipped. Approve this if you think it is ready.

**Comment by ejacox** [comment]
Jenkins, test this please.

**Pull request merged**
