### PR TITLE
Refactor Job._execute (resolves #973)

### LINKED ISSUE #973: Refactor Job._execute
Issue #963 brought up the issue where we were seeing jobs attempting to delete global files in use by other jobs (which shouldn't have been happening). @hannes-ucsc and I pinpointed it to being due to jobs saying they're completed and then being killed by bad worker before the job's temp dir was cleaned up. This left behind stale hard links that skew everything. Jobs should not be allowed to start the async update till their temp dirs have been cleaned up of all hard links.
I managed to reproduce teh bug in PR #972.

This Issue proposes to refactor Job._execute into 2 functions (names can be changed), 
1. Job._executor - A context manager that sets up stats and logging before the yield, and finishes up the stats and logging, and async updates the job after the yield
2. Job._runner - Actually runs the job, and serialises the next job(s)

worker.py will be modified to now have a nested context manager of Job._execute on the outside and job.fileStore on the inside such that the async update happens only after the cleanup has completed.

@benedictpaten  could you give us your comments on this when you can?

### PR DESCRIPTION
**Pull request by arkal**
resolves #973

refactored Job._execute into Job._executor and Job._runner and modified worker.py to use the new
context manager syntax of Job._executor.

### CODE REVIEW

**Comment by arkal** [comment]
Jenkins, test this please.

**Comment by arkal** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Can we change the commit message to 

```
Don't report job as success until caching cleaned up (fixes #972)

… by turning Job._execute() into a context manager that wraps the caching context manager.

Also, cacheInfo.jobState is now a defaultdict of dicts and not ints
```

**Comment by hannes-ucsc** [comment]
Build seems to hang. Gonna kill it. Check out 

```
AttributeError: '_JobState' object has no attribute 'jobSpecificFiles'
```

in the build log.

**Comment by arkal** [comment]
Yup that was stupidity on my part. Pushed a new one

**Comment by arkal** [comment]
@hannes-ucsc this is ready!

**Comment by arkal** [comment]
@hannes-ucsc this is ready! The only failure is a stats and logging error

**Comment by hannes-ucsc** [comment]
Build failure tracked as #978.

Jenkins, test this please.

**Comment by arkal** [comment]
Jenkins, test this please.

**Comment by arkal** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Build failure tracked as #978 for which a fix was merged into master since then.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Build failure tracked as #760.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by arkal** [comment]
This also resolved #963

**Pull request merged**
