### PR TITLE
Improve Python 3 compatibility

### PR DESCRIPTION
**Pull request by zero323**
This PR includes following changes:

- Adds [`six`](https://pypi.python.org/pypi/six) as a dependency.
- Replaces Python incompatible imports with equivalent `six` imports.
- Replaces `print` statements with `print` function calls.
- Replaces old-style ocatal literals (`0...`) with new-style literals (`0o...`).

### CODE REVIEW

**Comment by cket** [comment]
Jenkins, test this please

**Comment by benedictpaten** [comment]
Cool. Can someone please summarize for lagging edge folks like me how close this would get us to proper Python3.0 support? Importantly, do go Python3.0 would we need to break 2.7x support?

**Comment by cket** [comment]
@zero323 thanks for taking this on! It looks like there just a couple import problems on Jenkins:
`StringIO has no attribute 'StringIO'` in CWLTest.test_run_revsort and  `TypeError: 'Module_six_moves_urllib_parse' object is not callable` in the CGCloud provisioner tests. Can you see the Jenkins build outputs, by the way?

**Comment by zero323** [comment]
@cket My pleasure.

>  It looks like there just a couple import problems on Jenkins

I'll take a look at this when I have a spare moment. I have a family emergency so I typed most of that by heart in the waiting rooms so I might have mess something up.

> Can you see the Jenkins build outputs, by the way?

I don't think i have access.  I get:

> Access Denied
> 
> Please login to access job toil-pull-requests

no matter if I am marked as logged or not.

**Comment by zero323** [comment]
@cket I pushed some fixes but it looks like it requires authorization to execute tests.

@benedictpaten In general it is possible to achieve Python 3 compatibility without loosing Python 2 support. It requires some trade-offs and obviously you cannot use new language features. 

Regarding "how close" I have to admit I have no idea. At first glance there shouldn't be many blockers but as for now I am evaluating `toil` so I wouldn't depend on my opinion to much. The biggest advantage here is that, once this patch is applied, you can start testing against Python 3.x and see if things still work.

**Comment by cket** [comment]
Jenkins, ok to test

**Comment by cket** [comment]
@zero323 Jenkins should run automatically on this PR now@

**Comment by cket** [comment]
Jenkins, test this please

**Comment by cket** [comment]
@zero323 I think those test failures were sporadic, hopefully they all pass this time around

**Comment by cket** [comment]
@zero323 looks like the tests are all passing - thanks again! I'll take a closer look at this ASAP but I may not be able to get to it before the holidays

**Comment by benedictpaten** [comment]
Let's get this in.

**Comment by zero323** [comment]
@cket Thank you. I'll try to identify further blockers when I have some spare time.

**Comment by cket** [comment]
@zero323 awesome, I'm looking forward to getting full support! Thanks again.

**Pull request merged**
