### PR TITLE
Add examples of running prexisting workflows with Toil scripts.

### PR DESCRIPTION
**Pull request by bencvdb**
Addresses #2260. Provides examples of executing CWL and WDL workflows from a Toil script.

### CODE REVIEW

**Comment by DailyDreaming** [comment]
Maybe a mention about Toil running cwl/wdl directly vs. indirectly, as in the example. The wdl script has a Cromwell dependency that should be mentioned as well. Looks great though, thanks for adding this!

**Comment by bencvdb** [comment]
Given that these were on the same page as running CWL/WDL with Toil, I did not feel it was necessary to point them to another location where they can read up more. I did make sure to explicitly state that they were being run indirectly.

**Comment by DailyDreaming** [comment]
Alright, maybe I'd better explain my reasoning.  This is useful, but not quite the standard way that we want people to run cwl.  It might be useful to explain when something like this might be appropriate vs. running with `toil-cwl-runner`.

**Comment by DailyDreaming** [comment]
Due to Toil's move to `github.com/DataBiosphere`, we want to close PRs.  Merging this for now since it's just documentation, and little changes can be addressed in the future.

**Pull request merged**
