### PR TITLE
Check for venv in both py2 and 3. resolves #1985

### LINKED ISSUE #1985: Makefile does not detect virtualenv with Python 3
```
$ virtualenv venv3 -p python3.6
$ . venv3/bin/activate.fish
$ make prepare
A virtualenv must be active.
make: *** [check_venv] Error 1
```

Fix: https://stackoverflow.com/a/42580137
Related to #1780

### PR DESCRIPTION
**Pull request by ygrange**
I bumped into this issue today, and since it links to a solutiom (which seems to work in my install) I decided to put out a pull request for it.

### CODE REVIEW

**Comment by natanlao** [comment]
Jenkins, ok to test

**Comment by jessebrennan** [comment]
@ejacox @DailyDreaming one of you will need to approve

**Comment by mr-c** [comment]
Jenkins, okay to test

**Comment by ejacox** [comment]
Jenkins, test this please.

**Pull request merged**
