### PR TITLE
Fix Sphinx build warnings (resolves #594)

### LINKED ISSUE #594: Building Sphinx docs generates warnings
```
(venv)hannes-mbpr:docs hannes$ make clean html
rm -rf _build/*
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.2
making output directory...
/Users/hannes/workspace/bd2k/toil
/Users/hannes/workspace/bd2k/toil
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: 6 added, 0 changed, 0 removed
reading sources... [100%] tutorial                                                                                                                                                                          
/Users/hannes/workspace/bd2k/toil/docs/essentials.rst:183: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/src/toil/jobStores/abstractJobStore.py:docstring of toil.jobStores.abstractJobStore.AbstractJobStore:4: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/hannes/workspace/bd2k/toil/src/toil/jobStores/abstractJobStore.py:docstring of toil.jobStores.abstractJobStore.AbstractJobStore.updateFile:5: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/hannes/workspace/bd2k/toil/src/toil/jobStores/abstractJobStore.py:docstring of toil.jobStores.abstractJobStore.AbstractJobStore.updateFileStream:6: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/hannes/workspace/bd2k/toil/src/toil/jobStores/abstractJobStore.py:docstring of toil.jobStores.abstractJobStore.AbstractJobStore.writeSharedFileStream:5: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/hannes/workspace/bd2k/toil/src/toil/jobStores/abstractJobStore.py:docstring of toil.jobStores.abstractJobStore.AbstractJobStore.writeSharedFileStream:8: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/hannes/workspace/bd2k/toil/src/toil/jobStores/abstractJobStore.py:docstring of toil.jobStores.abstractJobStore.AbstractJobStore.writeSharedFileStream:11: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.addChildFn:3: WARNING: Inline emphasis start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.addChildFn:3: WARNING: Inline strong start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.addChildJobFn:4: WARNING: Inline emphasis start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.addChildJobFn:4: WARNING: Inline strong start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.addFollowOnFn:3: WARNING: Inline emphasis start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.addFollowOnFn:3: WARNING: Inline strong start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.addFollowOnJobFn:4: WARNING: Inline emphasis start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.addFollowOnJobFn:4: WARNING: Inline strong start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.getRootJobs:2: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.wrapFn:3: WARNING: Inline emphasis start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.wrapFn:3: WARNING: Inline strong start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.wrapJobFn:3: WARNING: Inline emphasis start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.wrapJobFn:3: WARNING: Inline strong start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.FileStore.readGlobalFile:4: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.FileStore.readGlobalFile:16: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.FunctionWrappingJob:3: WARNING: Inline emphasis start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.FunctionWrappingJob:3: WARNING: Inline strong start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.JobFunctionWrappingJob:5: WARNING: Inline emphasis start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.JobFunctionWrappingJob:5: WARNING: Inline strong start-string without end-string.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.EncapsulatedJob:5: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.checkJobGraphAcylic:5: ERROR: Undefined substitution referenced: "V|^2). It is O(|V".
/Users/hannes/workspace/bd2k/toil/src/toil/job.py:docstring of toil.job.Job.checkJobGraphAcylic:5: ERROR: Undefined substitution referenced: "E".
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:14: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:43: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:129: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:149: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:160: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:171: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:193: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:218: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:242: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:267: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:294: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:314: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:326: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:361: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:383: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:393: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:460: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:507: ERROR: Unexpected indentation.
/Users/hannes/workspace/bd2k/toil/docs/tutorial.rst:529: ERROR: Unexpected indentation.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] tutorial                                                                                                                                                                           
generating indices... genindex
highlighting module code... [100%] toil.batchSystems.abstractBatchSystem                                                                                                                                    
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/Users/hannes/workspace/bd2k/toil/docs/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 49 warnings.

Build finished. The HTML pages are in _build/html.
```

### PR DESCRIPTION
**Pull request by cket**
Fixes several rst formatting errors and an incorrectly listed html source in conf.py. 

Most errors involved the use of special rst characters in docstrings ( * and | ) and required backslashes to escape them. This makes the docstrings much uglier but I don't see a way around it.

### CODE REVIEW

**Comment by cket** [comment]
I opened this for review, but there is still 1 warning on my machine. Running 'make docs' gives 

/Users/cj/toil/docs/jobStore.rst:20: WARNING: autodoc: failed to import class u'AbstractJobStore' from module u'toil.batchSystems.abstractJobStore'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/cj/toil_env/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named abstractJobStore

This error wasn't reported in the original ticket and so may just be a problem on my machine

**Comment by hannes-ucsc** [comment]
Could you rebase? That should fix the build.

**Comment by hannes-ucsc** [comment]
```
``*args`` and ``**kwargs`` should be used instead of  \*args and \*\*kwargs

And can you also check if the \ at the line endings is necessary and if they are not, remove them?
```

**Comment by cket** [comment]
Jenkins, test this please.

**Pull request merged**
