### PR TITLE
fix failure in resolve_indirect_inner in cwltoil.py (resolves #1761)

### LINKED ISSUE #1761: cwltoil.py fails in resolve_indirect_inner for Workflow if substep is a workflow and some inputs are optional and empty
I have a Workflow job that uses workflow for the substep. If some inputs for the substep are optional and empty, it fails resolve_indirect_inner() in cwltoil.py:

    def resolve_indirect_inner(d):
        if isinstance(d, IndirectDict):
            r = {}
            for k, v in d.items():
                if isinstance(v, MergeInputs):
                    r[k] = v.resolve()
                else:
                    r[k] = v[1][v[0]]
            return r
        else:
            return d

The problem is at Line 103:

             r[k] = v[1][v[0]]

### PR DESCRIPTION
**Pull request by liuxf09**
fix failure in resolve_indirect_inner in cwltoil.py for Workflow if substep is a workflow and some inputs are optional and empty. see #1761

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
@ejacox I tried the trivial commit trick to initiate testing, but that didn't work :-/

**Comment by ejacox** [comment]
Jenkins add to whitelist

**Comment by ejacox** [comment]
Hmm.  Maybe the commit trick only works for PRs from team members. Let's see what adding a PR to the whitelist does.

**Pull request merged**
