### PR TITLE
Modify subprocessDockerCall to address 1959.

### PR DESCRIPTION
**Pull request by DailyDreaming**
Just allow "job" to be accepted as an *arg.  Addresses an issue with the subprocessDockerCall() that toil-vg uses.

### CODE REVIEW

**Comment by DailyDreaming** [comment]
EncryptedAWSJobStoreTest.testMultipartUploads broke for some reason.  This test has nothing to do with docker changes.

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Comment by joelarmstrong** [comment]
To be slightly more specific, it looks like you forgot to add the checkOutput param to the subprocessDockerCall function. Looks like the Jenkins tests didn't catch it for some reason, can you check that Jenkins is running the Docker tests on both the subprocess and API versions?

**Comment by DailyDreaming** [comment]
Joel's right about the checkOutput param, and it wasn't running the old unittests.  Sorry for the complication.  I've amended the code.

**Comment by ejacox** [comment]
@glennhickey is the code running now?

**Comment by glennhickey** [comment]
Yes, just dropped it in and toil-vg tests ran through.  Thanks

**Pull request merged**
