### PR TITLE
Display license information in `pip show` (fixes #1670)

### LINKED ISSUE #1670: "Pip show" doesn't contain information about Toil's license

### PR DESCRIPTION
**Pull request by natanlao**
Adds relevant `classifier` and `license` fields to `setup.py`.

### CODE REVIEW

**Comment by natanlao** [comment]
Jenkins, test this please

**Comment by natanlao** [comment]
Jenkins, test this please

**Comment by natanlao** [comment]
Jenkins, test this please.
(This is literally a two-line change to setup.py that makes *absolutely no functional changes*. Why.)

**Comment by mr-c** [comment]
```
SDBResponseError: SDBResponseError: 403 Forbidden
Query: select * from `deficit-[removed]--files` where ownerID='[removed]'
<?xml version="1.0"?>
<Response><Errors><Error><Code>InvalidClientTokenId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message></Error></Errors><RequestID>[removed]</RequestID></Response>
```

**Comment by mr-c** [comment]
@natanlao so hopefully just a transient error

maybe this will work:

Jenkins, test this please

**Comment by natanlao** [comment]
@mr-c Thank you! It looks like it was just a hiccup. Interestingly, I received the same error the [first time][0] this PR was tested.

 [0]: http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/1148/console

**Pull request merged**
