### PR TITLE
Asynchronous write caching fix (resolves #500, resolves #488)

### LINKED ISSUE #488: Toil default cache size is too small
The default 2.14G cache is too small for most purposes. Suggestion for enhancement could be to dynamically allocate it to 50%(or whatever fraction) of the free space on the volume that holds the localTempDir

```
import ctypes
import os
import platform
import sys

def get_free_space_mb(dirname):
    """Return folder/drive free space (in megabytes)."""
    if platform.system() == 'Windows':
        free_bytes = ctypes.c_ulonglong(0)
        ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(dirname), None, None, ctypes.pointer(free_bytes))
        return free_bytes.value / 1024 / 1024
    else:
        st = os.statvfs(dirname)
        return st.f_bavail * st.f_frsize / 1024 / 1024

cache_size = max(0.5*get_free_space(self. localTempDir), 2.14G)
```

Code was obtained from 

http://stackoverflow.com/questions/51658/cross-platform-space-remaining-on-volume-using-python

### LINKED ISSUE #500: Caching fails for large-ish files being written asynchronously to the jobStore
Following on from Arjun's tests we established that if a file was being written to the file store then it's local file could be cleaned from the cache, resulting in subsequent jobs trying to retrieve an incompletely written file from the jobStore.

### PR DESCRIPTION
**Pull request by benedictpaten**
Fixes bug, improves Job.FileStore tests. Thanks Arjun for finding and trapping bug!

Resolves #500 and #488

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Test failures are caused by inlining. Very likely unrelated.

**Comment by hannes-ucsc** [comment]
The conflicts were introduced by me merging #503 and the test failures are unrelated so I should deal with this from here.

**Comment by benedictpaten** [comment]
Okay, I added in one extra bit to this PR to make caching more usable, allowing per job caching requirements to be set. Please take over on resolving #502

**Comment by hannes-ucsc** [comment]
I resolved the conflicts. From the previous build I can already tell that cd7d1ef introduced a new test failure in Mesos. Back to you @benedictpaten.

**Comment by hannes-ucsc** [comment]
@benedictpaten The merge commit in your most recent push overrides some of my whitespace changes in helloWorldTest.py. It would have been easier and less destructive to rebase rather than merge.

http://stackoverflow.com/questions/9813816/git-pull-after-forced-update

Then again, I wasn't really following the multi-author protocol so I get what I deserve.

**Comment by benedictpaten** [comment]
Sorry, I realised this after I hit push. Sorry.

**Pull request merged**
