### PR TITLE
Add YARNBatchSystem to Toil (resolves #796)

### LINKED ISSUE #796: Add batch system for Apache YARN
[YARN](https://hadoop.apache.org/docs/r2.7.1/hadoop-yarn/hadoop-yarn-site/YARN.html) is the resource manager packaged with Hadoop 2.x. We use it on our internal cluster at Berkeley, as it is commonly installed by most Hadoop distros (e.g., CDH, HDP, etc).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-334)
┆Issue Number: TOIL-334

### PR DESCRIPTION
**Pull request by fnothaft**
Adds a YARNBatchSystem that enables Toil to run jobs on a cluster that is managed with the Apache Hadoop YARN resource manager. A job maps directly to a YARN application. Specifically, we run a batch command line under YARN using the YARN DistributedShell application. This way, we do not need to implement a YARN ApplicationManager, etc.

This is completely untested and doesn't have docs. I'll be adding tests in the next few days. @hannes-ucsc: IIRC, we'll need to add a YARN setup on Jenkins. I will ask you about this once I've got the tests done. I think it should be straightforward to do.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, skip this please.

**Comment by jpdna** [comment]
@fnothaft - in effort to test this and reproduce and resolve the remaining test failure you mentioned I have done the following:

1) cloned the Yarn fork from your repo, and checked out the `yarn` branch on which  this PR is based, and setup virtualenv for toil then run `make test` as described at `http://toil.readthedocs.io/en/latest/installation.html#building-testing`

2) installed Hadoop-2.6.4 in a local dir and set HADOOP_HOME to it.    Is there more config for Hadoop I should do?

3) I tried starting Yarn daemons with `./sbin/start-yarn.sh` prior to running `make test` on toil, but get lots of erros about `java.net.BindException: Problem binding to [0.0.0.0:8031] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException`

If I don't start YARN first, the tests seem to run more happily, but in that case the end of the test output seems stuck at end producing forever:
```
6/05/17 10:29:52 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
16/05/17 10:29:53 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
16/05/17 10:29:54 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
...
```

can you point me to the correct Yarn setup here for testing, which test to run, and what the current test failure  you are getting is so I know when I reproduce it properly?

`

**Comment by jpdna** [comment]
Just pinging on this - @fnothaft just point me in right direction when you have a chance - see above.

**Comment by fnothaft** [comment]
@jpdna that should be sufficient. Can you test your YARN installation? E.g., can you ping the YARN web UI on your machine, can you launch a simple application...?

**Comment by jpdna** [comment]
I can see the Yarn UI, though didn't run a job as yet.

I'll try again and get more log info / test output to you.

**Comment by jpdna** [comment]
After running, `./sbin/start-yarn.sh ` Yarn UI is up and I manually ran yarn distributed shell like
```
./yarn org.apache.hadoop.yarn.applications.distributedshell.Client -jar $YARN_DS/hadoop-yarn-applications-distributedshell-$YARN_VERSION.jar -shell_command uptime
```
and seemed to work

My attempt here to next run `make test` inside of the toil directory as described in my earlier comment.

Some relevant output from `make test ` is
```
src/toil/__init__.py::toil.physicalMemory PASSED
src/toil/common.py::toil.common.parseSetEnv PASSED
src/toil/realtimeLogger.py::toil.realtimeLogger.RealtimeLogger PASSED
src/toil/resource.py::toil.resource.ModuleDescriptor Traceback (most recent call last):
  File "/tmp/tmpphjIJV/foo.py", line 1, in <module>
    from toil.resource import ModuleDescriptor
ImportError: No module named toil.resource
FAILED
src/toil/test/__init__.py::toil.test.make_tests PASSED
src/toil/test/batchSystems/batchSystemTest.py::MesosBatchSystemTest::testAvailableCores SKIPPED
src/toil/test/batchSystems/batchSystemTest.py::MesosBatchSystemTest::testCheckResourceRequest SKIPPED
src/toil/test/batchSystems/batchSystemTest.py::MesosBatchSystemTest::testGetRescueJobFrequency SKIPPED
src/toil/test/batchSystems/batchSystemTest.py::MesosBatchSystemTest::testRunJobs SKIPPED
src/toil/test/batchSystems/batchSystemTest.py::MesosBatchSystemTest::testSetEnv SKIPPED
src/toil/test/batchSystems/batchSystemTest.py::YARNBatchSystemTest::testAvailableCores 16/05/18 15:43:31 INFO resourcemanager.ResourceManager: STARTUP_MSG: 
/************************************************************

```
and later
```
16/05/18 15:43:32 INFO service.AbstractService: Service ResourceManager failed in state STARTED; cause: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.net.BindException: Problem binding to [0.0.0.0:8031] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.net.BindException: Problem binding to [0.0.0.0:8031] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
        at org.apache.hadoop.yarn.factories.impl.pb.RpcServerFactoryPBImpl.getServer(RpcServerFactoryPBImpl.java:139)
        at org.apache.hadoop.yarn.ipc.HadoopYarnProtoRPC.getServer(HadoopYarnProtoRPC.java:65)
        at org.apache.hadoop.yarn.ipc.YarnRPC.getServer(YarnRPC.java:54)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceTrackerService.serviceStart(ResourceTrackerService.java:162)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.service.CompositeService.serviceStart(CompositeService.java:120)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$RMActiveServices.serviceStart(ResourceManager.java:592)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.startActiveServices(ResourceManager.java:1007)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$1.run(ResourceManager.java:1048)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$1.run(ResourceManager.java:1044)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1656)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.transitionToActive(ResourceManager.java:1044)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceStart(ResourceManager.java:1084)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.main(ResourceManager.java:1219)
Caused by: java.net.BindException: Problem binding to [0.0.0.0:8031] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:720)
        at org.apache.hadoop.ipc.Server.bind(Server.java:424)
        at org.apache.hadoop.ipc.Server$Listener.<init>(Server.java:573)
        at org.apache.hadoop.ipc.Server.<init>(Server.java:2206)
        at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:944)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:537)
        at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:512)
        at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:789)
        at org.apache.hadoop.yarn.factories.impl.pb.RpcServerFactoryPBImpl.createServer(RpcServerFactoryPBImpl.java:169)
        at org.apache.hadoop.yarn.factories.impl.pb.RpcServerFactoryPBImpl.getServer(RpcServerFactoryPBImpl.java:132)
        ... 17 more
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.apache.hadoop.ipc.Server.bind(Server.java:407)
        ... 25 more
16/05/18 15:43:32 INFO resourcemanager.ResourceManager: Transitioning to standby state
16/05/18 15:43:32 INFO resourcemanager.ResourceManager: Transitioned to standby state
16/05/18 15:43:32 FATAL resourcemanager.ResourceManager: Error starting ResourceManager
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.net.BindException: Problem binding to [0.0.0.0:8031] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
        at org.apache.hadoop.yarn.factories.impl.pb.RpcServerFactoryPBImpl.getServer(RpcServerFactoryPBImpl.java:139)
        at org.apache.hadoop.yarn.ipc.HadoopYarnProtoRPC.getServer(HadoopYarnProtoRPC.java:65)
        at org.apache.hadoop.yarn.ipc.YarnRPC.getServer(YarnRPC.java:54)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceTrackerService.serviceStart(ResourceTrackerService.java:162)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.service.CompositeService.serviceStart(CompositeService.java:120)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$RMActiveServices.serviceStart(ResourceManager.java:592)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.startActiveServices(ResourceManager.java:1007)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$1.run(ResourceManager.java:1048)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$1.run(ResourceManager.java:1044)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1656)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.transitionToActive(ResourceManager.java:1044)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceStart(ResourceManager.java:1084)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.main(ResourceManager.java:1219)
Caused by: java.net.BindException: Problem binding to [0.0.0.0:8031] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

```
@fnothaft  - I am emailing you the full output I saved to a file.

**Comment by DailyDreaming** [comment]
This seems unlikely to be revived.  Closing this unless someone posts an objection.

**Pull request closed without merging**
