### PR TITLE
Nested promises and immutable user file store (resolves #365, resolves #375, resolves #373, resolves #398)

### LINKED ISSUE #365: Files put in global file store not in global file store
I'm putting files in the global file store in a child job, returning their IDs thouugh the promise mechanism into the follow-on job's arguments, and then the follow-on job is complaining that it can't get the files.

The code I am using is here: https://github.com/adamnovak/hgvm/blob/a97b0cb3835fd81078a580ac17d2843659baf84c/getAltReads.py

The messages I am getting are here:
```
[anovak@kolossus hgvm]$ rm -Rf tree && ./getAltReads.py ./tree `pwd`/dl --maxCores 64 --regions BRCA1
Starting server
Server started
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/bake-off/hgvm', name='getAltReads', extension='.py').
Sending log from master
INFO:realtime:This is the master
INFO:toil.lib.bioio:Logging set at level: INFO
INFO:toil.common:Using the single machine batch system
INFO:toil.jobStores.fileJobStore:Jobstore directory is: /hive/users/anovak/ga4gh/bake-off/hgvm/tree
INFO:realtime:This is the master
INFO:toil.batchSystems.singleMachine:Setting up the thread pool with 640 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 64.
INFO:toil.common:Written the environment for the jobs to the environment file
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/cluster/home/anovak/.local/lib/python2.7/site-packages', name='toil.job', extension='.pyc').
INFO:toil.leader:Checked batch system has no running jobs and no updated jobs
INFO:toil.leader:Found 1 jobs to start and 0 jobs with successors to run
INFO:toil.leader:Starting the main loop
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree v/r/jobcI22fw'.
INFO:realtime:Starting download
INFO:realtime:Got 2 sample URLs
INFO:realtime:Making child for BRCA1 x NA06985: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06985
INFO:realtime:Making child for BRCA1 x NA06984: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06984
INFO:realtime:Done making children
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree i/L/jobrZzC1R'.
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree i/V/job4uJOM_'.
INFO:realtime:Supposed to download ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06985 ranges ['chr17:43044294-43125482'] to /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06985.bam
INFO:realtime:Supposed to download ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06984 ranges ['chr17:43044294-43125482'] to /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06984.bam
INFO:realtime:Need URLs: ['ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06985/alignment/NA06985.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram']
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree k/9/joblK0HtL'.
INFO:realtime:Need URLs: ['ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06984/alignment/NA06984.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram']
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree 4/d/jobCWAmtb'.
INFO:realtime:Trying to download chr17:43044294-43125482 from ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06985/alignment/NA06985.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram
INFO:realtime:Trying to download chr17:43044294-43125482 from ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06984/alignment/NA06984.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree 6/9/jobMjexml'.
INFO:toil.batchSystems.singleMachine:Executing command: '/cluster/home/anovak/python/bin/python2.7 -E /cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py /hive/users/anovak/ga4gh/bake-off/hgvm/tree u/C/jobHf0cen'.
INFO:realtime:Building /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06984.bam from IDs ['4/d/jobCWAmtb/g/tmpfbThnV.tmp']
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 6/9/jobMjexml
WARNING:toil.leader:Reporting file: 6/9/jobMjexml
WARNING:toil.leader:6/9/jobMjexml:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:6/9/jobMjexml:	INFO:toil.jobStores.fileJobStore:Jobstore directory is: /hive/users/anovak/ga4gh/bake-off/hgvm/tree
WARNING:toil.leader:6/9/jobMjexml:	WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/bake-off/hgvm/getAltReads.pyc'
WARNING:toil.leader:6/9/jobMjexml:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/bake-off/hgvm', name='getAltReads', extension='.pyc')
WARNING:toil.leader:6/9/jobMjexml:	INFO:realtime:Building /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06984.bam from IDs ['4/d/jobCWAmtb/g/tmpfbThnV.tmp']
WARNING:toil.leader:6/9/jobMjexml:	Traceback (most recent call last):
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py", line 238, in main
WARNING:toil.leader:6/9/jobMjexml:	    jobStore=jobStore)
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 862, in _execute
WARNING:toil.leader:6/9/jobMjexml:	    returnValues = self.run(fileStore)
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 983, in run
WARNING:toil.leader:6/9/jobMjexml:	    return userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:6/9/jobMjexml:	  File "/hive/users/anovak/ga4gh/bake-off/hgvm/getAltReads.py", line 480, in concatAndSortBams
WARNING:toil.leader:6/9/jobMjexml:	    input_files = [job.fileStore.readGlobalFile(bam_id) for bam_id in bam_ids]
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 399, in readGlobalFile
WARNING:toil.leader:6/9/jobMjexml:	    self.jobStore.readFile(fileStoreID, localFilePath)
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 157, in readFile
WARNING:toil.leader:6/9/jobMjexml:	    self._checkJobStoreFileID(jobStoreFileID)
WARNING:toil.leader:6/9/jobMjexml:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 293, in _checkJobStoreFileID
WARNING:toil.leader:6/9/jobMjexml:	    raise NoSuchFileException("File %s does not exist in jobStore" % jobStoreFileID)
WARNING:toil.leader:6/9/jobMjexml:	NoSuchFileException: The file 'File 4/d/jobCWAmtb/g/tmpfbThnV.tmp does not exist in jobStore' does not exist
WARNING:toil.leader:6/9/jobMjexml:	Exiting the worker because of a failed job on host kolossus
WARNING:toil.leader:6/9/jobMjexml:	ERROR:__main__:Exiting the worker because of a failed job on host kolossus
WARNING:toil.leader:6/9/jobMjexml:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 6/9/jobMjexml to 0
WARNING:toil.leader:Job: 6/9/jobMjexml is completely failed
INFO:realtime:Building /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06985.bam from IDs ['k/9/joblK0HtL/g/tmpXWMxPK.tmp']
WARNING:toil.leader:The job seems to have left a log file, indicating failure: u/C/jobHf0cen
WARNING:toil.leader:Reporting file: u/C/jobHf0cen
WARNING:toil.leader:u/C/jobHf0cen:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:u/C/jobHf0cen:	INFO:toil.jobStores.fileJobStore:Jobstore directory is: /hive/users/anovak/ga4gh/bake-off/hgvm/tree
WARNING:toil.leader:u/C/jobHf0cen:	WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/bake-off/hgvm/getAltReads.pyc'
WARNING:toil.leader:u/C/jobHf0cen:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/bake-off/hgvm', name='getAltReads', extension='.pyc')
WARNING:toil.leader:u/C/jobHf0cen:	INFO:realtime:Building /cluster/home/anovak/hive/ga4gh/bake-off/hgvm/dl/BRCA1/NA06985.bam from IDs ['k/9/joblK0HtL/g/tmpXWMxPK.tmp']
WARNING:toil.leader:u/C/jobHf0cen:	Traceback (most recent call last):
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/worker.py", line 238, in main
WARNING:toil.leader:u/C/jobHf0cen:	    jobStore=jobStore)
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 862, in _execute
WARNING:toil.leader:u/C/jobHf0cen:	    returnValues = self.run(fileStore)
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 983, in run
WARNING:toil.leader:u/C/jobHf0cen:	    return userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:u/C/jobHf0cen:	  File "/hive/users/anovak/ga4gh/bake-off/hgvm/getAltReads.py", line 480, in concatAndSortBams
WARNING:toil.leader:u/C/jobHf0cen:	    input_files = [job.fileStore.readGlobalFile(bam_id) for bam_id in bam_ids]
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 399, in readGlobalFile
WARNING:toil.leader:u/C/jobHf0cen:	    self.jobStore.readFile(fileStoreID, localFilePath)
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 157, in readFile
WARNING:toil.leader:u/C/jobHf0cen:	    self._checkJobStoreFileID(jobStoreFileID)
WARNING:toil.leader:u/C/jobHf0cen:	  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 293, in _checkJobStoreFileID
WARNING:toil.leader:u/C/jobHf0cen:	    raise NoSuchFileException("File %s does not exist in jobStore" % jobStoreFileID)
WARNING:toil.leader:u/C/jobHf0cen:	NoSuchFileException: The file 'File k/9/joblK0HtL/g/tmpXWMxPK.tmp does not exist in jobStore' does not exist
WARNING:toil.leader:u/C/jobHf0cen:	Exiting the worker because of a failed job on host kolossus
WARNING:toil.leader:u/C/jobHf0cen:	ERROR:__main__:Exiting the worker because of a failed job on host kolossus
WARNING:toil.leader:u/C/jobHf0cen:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job u/C/jobHf0cen to 0
WARNING:toil.leader:Job: u/C/jobHf0cen is completely failed
INFO:toil.leader:Only failed jobs and their dependents (2 total) are remaining, so exiting.
INFO:toil.leader:Finished the main loop
INFO:toil.leader:Waiting for stats and logging collator process to finish
INFO:toil.leader:Stats/logging finished collating in 0.019984960556 seconds
Traceback (most recent call last):
  File "./getAltReads.py", line 530, in <module>
    sys.exit(main())
  File "./getAltReads.py", line 524, in main
    Job.Runner.startToil(root_job,  options)
  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/job.py", line 356, in startToil
    return mainLoop(config, batchSystem, jobStore, rootJob)
  File "/cluster/home/anovak/.local/lib/python2.7/site-packages/toil/leader.py", line 508, in mainLoop
    raise FailedJobsException( config.jobStore, totalFailedJobs )
toil.leader.FailedJobsException: The job store '/hive/users/anovak/ga4gh/bake-off/hgvm/tree' contains 2 failed jobs
```

### LINKED ISSUE #373: Allow nested promises

### LINKED ISSUE #375: Create caching interface
Depends on #374, should obey resource limits

### LINKED ISSUE #398: quick-start guide code is broken
The code in the Scripting Quick Start is broken because it uses optparse

### PR DESCRIPTION
**Pull request by benedictpaten**
This has not pulled in master for awhile, also the Azure and AWS jobStores are broken by a small number of changes. However, this pull request makes it possible to pass promises in an arbitrary, nested fashion, makes the user facing Job.FileStore interface essentially immutable and paves the way for robust caching. I am proposing assigning to Hannes/CJ to fix AWS and Azure support and to pull in master. Note this code really reorganises the serialisation process, so it is likely to heavily conflict with CJs changes.

### CODE REVIEW

**Comment by benedictpaten** [comment]
Actually, I will solve the merge conflicts, doesn't seem to bad. Standby.

**Comment by benedictpaten** [comment]
Okay, back to Hannes. All merge conflicts resolved okay, I think.

**Comment by hannes-ucsc** [comment]
The build timed out. I will temporarily remove Azure job store.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Still timing out. Presumably in the sort tests.

**Comment by hannes-ucsc** [comment]
Benedict, you will want to merge again from master to get the encryption extra. Otherwise the builds will fail right away.

**Comment by benedictpaten** [comment]
Okay, I'm doing this... are you saying the sort tests are failing because of me? They work fine (and fast) using the file system fileStore.

**Comment by hannes-ucsc** [comment]
Increased timeout to 60min, enabled verbose logging.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
We don't know if the tests are failing. Jenkins killed the build because it exceeded the 45 min timeout that I configured.  The problem is that the tail of the build output isn't flushed when  Jenkins cancels the build so it is hard to say which exact test is taking too long or is hung. As mentioned above, I increased the timeout and enabled verbose logging. This will give us clarity.

**Comment by hannes-ucsc** [comment]
Made a typo. Cancelled the build. Trying again.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
So it is toil.test.sort.sortTest.SortTest.testAwsMesos that is getting into an infinite loop.

**Comment by hannes-ucsc** [comment]
I'll disable Mesos, AWS and Azure on the build plan for the time being.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by benedictpaten** [comment]
Yes, as I said in my earlier email - the AWS jobstore is broken right now,
but I'm hoping you can fix this when you have time.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by benedictpaten** [comment]
Just pulled in latest master - AWS and Azure files stores still broken, I think.

**Comment by hannes-ucsc** [comment]
I've been asked to finish this off. Going multi-author. No more force pushes please.

**Comment by hannes-ucsc** [comment]
The tests now take 1h:13min. I'll still merge this tomorrow after a clean-up and rebase of the commits.

**Comment by hannes-ucsc** [comment]
It would be helpful if that new PR be based on master not this branch.

**Pull request merged**
