### PR TITLE
Fix bug in testAsyncWriteWithCaching (resolves #1344)

### LINKED ISSUE #1344: Sporadic caching failures
Seen on master, unfortunately.
http://jenkins.cgcloud.info/job/toil-branches/branch/master/286/console
It seems more common on the AWS job store, I will update this ticket with links for those failures once I've found them.

### PR DESCRIPTION
**Pull request by arkal**
resolves #1344

The monkey patch to job.fileStore.jobStore.updateFileStream was propagating to
the next job and causing the next job to wait 20s to resolve the promise it was
passed.  Monkey patching job.fileStore.HarbingerFile.read limits the patch to the
scope of the current job and fixes this issue.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by arkal** [comment]
Awh yeah. @hannes-ucsc @cket this passed tests. Do you want to run the tests a few more times to prove it really is fixed? Maybe just the unit tests and not the integration ones?

**Comment by arkal** [comment]
doing it anyway

**Comment by arkal** [comment]
Jenkins, test this please.

**Comment by arkal** [comment]
Jenkins, test this please.

**Comment by cket** [comment]
jenkins, test this please

**Pull request merged**
