### PR TITLE
Mount all of /var/ into Toil Appliance

### PR DESCRIPTION
**Pull request by cket**

### CODE REVIEW

**Comment by chapmanb** [comment]
Brilliant, thanks so much for this. Hopefully it'll get cwltoil working with the default directories.

**Comment by cket** [comment]
@chapmanb good news, I successfully ran the test BCBio pipeline w/ Mesos and AWS using the changes in 587871c. I'm going to try with autoscaling now

**Comment by cket** [comment]
This fix worked with Autoscaling as well!

**Comment by chapmanb** [comment]
Cj;
Brilliant, thanks so much. I can confirm this works for me as well with the test bcbio repository, using this workflow: https://github.com/chapmanb/bcbio-nextgen/tree/master/scripts/ansible#running-with-toil). Awesome, I'm fired up to have this working. I'll start trying some larger tests and report back as well. Thank you again for all the help with this.

**Comment by ohofmann** [comment]
I think I'm going to have a little happy dance here. Thanks so much for all your work on this.

**Pull request merged**
