### PR TITLE
issue1929/correction_slurm.py

### PR DESCRIPTION
**Pull request by lassancejm**
make squeue invocation universally compatible to solve issue #1929

### CODE REVIEW

**Comment by benedictpaten** [comment]
jenkins, test this please

**Comment by lassancejm** [comment]
Could somebody re-test this? I just got reminded when testing release 3.13.0 that the correction has not been made. 
Thanks!

**Comment by DailyDreaming** [comment]
Jenkins, please test this.

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Comment by DailyDreaming** [comment]
@lassancejm Our usual "Jenkins, test this please." incantation doesn't appear to be working (assuming this is because your branch is outside of our organization).  Could you add or subtract a newline somewhere and push a new commit to relaunch the tests?

**Comment by ejacox** [comment]
Jenkins, test this please.

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Comment by lassancejm** [comment]
Glad this made it through!

**Comment by DailyDreaming** [comment]
I was glad to add it!  It seemed like a pretty straight forward fix, despite jenkins not returning tests, so I thought it would be harmless to merge.

Unfortunately, one of our unittests is now returning an error:

http://jenkins.cgcloud.info/job/toil-pull-requests/3736/testReport/src.toil.test.batchSystems.batchSystemTest/SlurmBatchSystemTest/testRunJobs
```
Stacktrace

Traceback (most recent call last):
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/test/batchSystems/batchSystemTest.py", line 144, in testRunJobs
    self.assertEqual(set(runningJobIDs), {job1, job2})
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 796, in assertSetEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Items in the second set but not the first:
0
1

Standard Output

2018-03-01 18:21:45,901 - toil.test - INFO - Setting up toil.test.batchSystems.batchSystemTest.SlurmBatchSystemTest.testRunJobs ...
2018-03-01 18:21:45,901 - toil.batchSystems.singleMachine - WARNING - Limiting maxMemory to physically available memory (31624953856).
2018-03-01 18:21:45,902 - toil.common - INFO - Created the workflow directory at /mnt/ephemeral/tmp/toil-e4c9a731-c83e-4d26-82bc-785d88cba7db-dd1bac9cb23792a632bd6ee157719517
2018-03-01 18:22:06,982 - toil.test - INFO - Tore down toil.test.batchSystems.batchSystemTest.SlurmBatchSystemTest.testRunJobs

Standard Error

INFO:toil.test:Setting up toil.test.batchSystems.batchSystemTest.SlurmBatchSystemTest.testRunJobs ...
WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (31624953856).
INFO:toil.common:Created the workflow directory at /mnt/ephemeral/tmp/toil-e4c9a731-c83e-4d26-82bc-785d88cba7db-dd1bac9cb23792a632bd6ee157719517
INFO:toil.test:Tore down toil.test.batchSystems.batchSystemTest.SlurmBatchSystemTest.testRunJobs
```

So I have to take a look at the test to see what it's doing and if it isn't a problem with the test itself (since your code seems correct from what I can tell).  However, there may be a chance that we have to revert the change.

**Comment by lassancejm** [comment]
This is odd ; let me know if there is anything I can do to help.

**Comment by DailyDreaming** [comment]
I will look into this a bit more later.  I really do think it's a problem with the test.  It's been temporarily reverted in the meantime to quell the failing test.

**Pull request merged**
