### PR TITLE
Allow job wrapping of more types of functions (resolves #264)

### LINKED ISSUE #264: Allow jobs to wrap class functions, nested functions and lambda functions
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-307)
┆Issue Number: TOIL-307

### PR DESCRIPTION
**Pull request by benedictpaten**
I am having issues with eclipse testing the utilTest, seeing if Jenkins will pass the tests.

### CODE REVIEW

**Comment by benedictpaten** [comment]
Okay, I'm not understanding the output here - as it claims a test failed but lists 0 tests failed. I would expect the jobTest to fail until we make dill-0.2.4 is made a dependency. To do this do I just edit setup.py?

**Comment by hannes-ucsc** [comment]
http://jenkins.cgcloud.info/job/toil/237/console

utilsTest hung

**Comment by hannes-ucsc** [comment]
> To do this do I just edit setup.py?

Yes

**Comment by benedictpaten** [comment]
Still fiddling around with this, hoping to get at least a fully working prototype shortly. I think we'll still need the resource manager class for tracking the module from which the function derives.

**Comment by cket** [comment]
I've been thinking about this issue. If I understand this correctly, the main problem is that these functions all could need information that isn't necessarily defined within them. Then when the function is pickled and run in a separate interpreter, this outside information is completely lost. Is that true?

**Comment by hannes-ucsc** [comment]
Continued in #505

**Pull request closed without merging**
