### PR TITLE
Fixes jobStore "clean" method for service jobs (Resolves #908).

### LINKED ISSUE #908: NoSuchJobException in service tests
http://jenkins.cgcloud.info/job/toil-branches/branch/master/159/testReport/junit/src.toil.test.src.jobServiceTest/JobServiceTest/testServiceWithCheckpoints/

```
NoSuchJobException: The job 'J/X/jobWhAf5O' does not exist
```

### PR DESCRIPTION
**Pull request by benedictpaten**

### CODE REVIEW

**Comment by benedictpaten** [comment]
Aside from the file store tests failing, all the other tests passed. Will merge in a few hours..

**Comment by hannes-ucsc** [comment]
s/Resolves/resolves in commit title

**Comment by hannes-ucsc** [comment]
And no period at the end of commit title, please.

**Comment by hannes-ucsc** [comment]
Otherwise +1 from me.

**Comment by benedictpaten** [comment]
Okay, thanks. Will merge this one as do not see as critical to fix, but will get style right next time.

**Pull request merged**
