### PR TITLE
Revert "Set mesosMasterAddress default to private IP (resolves #1664)"

### LINKED ISSUE #1664: mesosMasterAddress should default to leader's private IP, not localhost
When starting a workflow on the leader node of a cluster for autoscaling one needs to specify the option `mesosMasterAddress=<my_local_IP_address>:5050` because the default (localhost:5050) is not useful at all and causes the workflow to fail more or less ambiguously. 

To get the local IP address without any external dependencies the following code hunk from [here](http://stackoverflow.com/a/24196955) seems to be the most robust and straight forward.

```
import socket
import fcntl
import struct

def get_ip_address(ifname):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    return socket.inet_ntoa(fcntl.ioctl(
        s.fileno(),
        0x8915,  # SIOCGIFADDR
        struct.pack('256s', ifname[:15])
    )[20:24])

get_ip_address('eth0')
```

### PR DESCRIPTION
**Pull request by jessebrennan**
This PR was not ready to be merged.

### CODE REVIEW

**Comment by jessebrennan** [comment]
@ejacox I was thinking we could revert this PR and then I could resume work on the old one to figure out what may be causing a failure.

**Comment by ejacox** [comment]
Sounds good @jessebrennan.

**Comment by jessebrennan** [comment]
@ejacox This is weird. How could reverting back to a previous version of master cause a failure? Unless either master was broken before, or something is wrong with Jenkins.

**Comment by jessebrennan** [comment]
Jenkins, test this please

**Comment by jessebrennan** [comment]
@ejacox looks like this is passing as expected and can be merged. I will continue the fix on the other branch.

**Comment by jessebrennan** [comment]
In offline discussion with @ejacox we decided to just leave as is and the new PR with override.

**Pull request closed without merging**
