### PR TITLE
Set mesosMasterAddress default to private IP (resolves #1664)

### LINKED ISSUE #1664: mesosMasterAddress should default to leader's private IP, not localhost
When starting a workflow on the leader node of a cluster for autoscaling one needs to specify the option `mesosMasterAddress=<my_local_IP_address>:5050` because the default (localhost:5050) is not useful at all and causes the workflow to fail more or less ambiguously. 

To get the local IP address without any external dependencies the following code hunk from [here](http://stackoverflow.com/a/24196955) seems to be the most robust and straight forward.

```
import socket
import fcntl
import struct

def get_ip_address(ifname):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    return socket.inet_ntoa(fcntl.ioctl(
        s.fileno(),
        0x8915,  # SIOCGIFADDR
        struct.pack('256s', ifname[:15])
    )[20:24])

get_ip_address('eth0')
```

### PR DESCRIPTION
**Pull request by jessebrennan**
Note this is the same as #1668 but reopened.

### CODE REVIEW

**Comment by jessebrennan** [comment]
Jenkins, test this please.

**Comment by joelarmstrong** [comment]
Sort of off-topic, but this test failure looks like a repeat of #1700. It looks like there's some (unrelated) infinite-loop problem with the GoogleJobStore, but it's hard to pin it down. I wonder if, instead of using the jenkins timeout, which unceremoniously and silently kills everything, we could use a [pytest timeout](https://pypi.python.org/pypi/pytest-timeout), so we know which test failed? That would help narrow down the possibilities--these flaky tests are super annoying and we should track them down if possible.

**Comment by jessebrennan** [comment]
Joel that's a great idea,  I didn't even know that was an option!

Also are you suggesting that my code is not responsible for the failure?

On Jun 23, 2017 9:48 PM, "Joel Armstrong" <notifications@github.com> wrote:

Sort of off-topic, but this test failure looks like a repeat of #1700
<https://github.com/BD2KGenomics/toil/issues/1700>. It looks like there's
some (unrelated) infinite-loop problem with the GoogleJobStore, but it's
hard to pin it down. I wonder if, instead of using the jenkins timeout,
which unceremoniously and silently kills everything, we could use a pytest
timeout <https://pypi.python.org/pypi/pytest-timeout>, so we know which
test failed? That would help narrow down the possibilities--these flaky
tests are super annoying and we should track them down if possible.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/BD2KGenomics/toil/pull/1731#issuecomment-310813970>,
or mute
the thread

**Comment by joelarmstrong** [comment]
On closer inspection it looks like the failure is not in the Google jobStore tests but in the sort tests, so maybe this is caused by your code after all. My bad! I think the point about pytest timeouts still stands, though.

(I think the failure is probably caused by [the mesos test support libs](https://github.com/BD2KGenomics/toil/blob/master/src/toil/batchSystems/mesos/test/__init__.py#L68), which specify a master IP of 127.0.0.1. Mesos slaves reject any master that advertises a different IP than it's contacted on. Changing those to use the same "get external IP" logic will probably fix things.)

**Comment by jessebrennan** [comment]
Jenkins, test this please

**Comment by jessebrennan** [comment]
Jenkins test this please

**Comment by jessebrennan** [comment]
Well cool! Looks like this is working now too! @ejacox ready for review

**Comment by ejacox** [comment]
It looks like a merge took out the call to getLocalIP.

**Comment by jessebrennan** [comment]
@ejacox Hah! okay, I'm on it. Thanks

**Comment by jessebrennan** [comment]
It looks like all of the integration test failures are due to the IAM outage

**Comment by jessebrennan** [comment]
HAH! Okay I'm going to squash and rebase this terribly ugly branch

**Comment by jessebrennan** [comment]
Ahhhh... Down to just four beautiful commits. This is ready for review @ejacox

**Comment by jessebrennan** [comment]
I ran the failed test (src.toil.test.provisioners.aws.awsProvisionerTest.AWSAutoscaleTest.testSpotAutoScale) locally and it passed fine. My suspicion is that the failure was transient, but I don't have a good reason why.

Also it is suspicious that _this_ test failed given that it was modified to test the new default value of `--mesosMaster`. I don't think the failure was related however because if it was, the staticAutoScaleTest would have probably failed as well. 

I will test again. Jenkins test this please.

**Comment by jessebrennan** [comment]
@ejacox merge?

**Pull request merged**
