### PR TITLE
Multiple fixes, aimed at allowing restart and utils to operation

### PR DESCRIPTION
**Pull request by benedictpaten**
properly

Fixed toil restart process. 
Fixed toilRestart, toilStats and toilStatus and added utilsTest to test
them
Added --restart option and --useExistingOptions to toil options
Added some TODOs on options
Added "create" option to jobStores, AWS currently broken.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Looks like the tests are hanging. I will kill tests and restart.

**Comment by benedictpaten** [comment]
The AWS batch system is broken right now.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Tests hung again. Mesos executor logs show

```
DEBUG:__main__:Invoking command: '/mnt/ephemeral/workspace/toil/venv/bin/python2.7 -E /mnt/ephemeral/workspace/toil/src/toil/worker.py aws:us-west-2:sort-test-998bc8b5-7240-4fbe-9e43-55104d253300 512f5090-910d-4072-b2d1-68e90a5eb65e'
Traceback (most recent call last):
  File "/mnt/ephemeral/workspace/toil/src/toil/worker.py", line 431, in <module>
    main()
  File "/mnt/ephemeral/workspace/toil/src/toil/worker.py", line 124, in main
    jobStore = loadJobStore(jobStoreString)
  File "/mnt/ephemeral/workspace/toil/src/toil/common.py", line 393, in loadJobStore
    return AWSJobStore( region, namePrefix, config=config, create=create )
  File "/mnt/ephemeral/workspace/toil/src/toil/jobStores/awsJobStore.py", line 104, in __init__
    self.checkJobStoreCreation(create, False, region + " " + namePrefix)
  File "/mnt/ephemeral/workspace/toil/src/toil/jobStores/abstractJobStore.py", line 66, in checkJobStoreCreation
    "is nothing to restart." % jobStoreString)
toil.jobStores.abstractJobStore.JobStoreCreationException: The job store 'us-west-2 sort-test-998bc8b5-7240-4fbe-9e43-55104d253300' does not exist, so there is nothing to restart.
```

which is expected until I fix Benedict's TODO in AWSJobStore.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Resume doesn't work in sort and I can't figure out why.

**Comment by benedictpaten** [comment]
That's odd. Does it work for the file system batch system?

**Comment by hannes-ucsc** [comment]
No. Did it work originally when you first filed the PR. In that case I would suspect a merge error on my end.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Pull request merged**
