### PR TITLE
Tweak bucket creation and versioning configuration (resolves #1272)

### LINKED ISSUE #1272: Assertion error in bucket creation
http://jenkins.cgcloud.info/job/toil-pull-requests/2032/testReport/src.toil.test.jobStores.jobStoreTest/AWSJobStoreTest/test_testImportExportFile__otherCls_awsjobstoretest__size_one/

Note that the assertion message is mangled by  pytest's weird assertion introspection.

### PR DESCRIPTION
**Pull request by hannes-ucsc**
resolves #1272

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Ready for review, @cket. The commit title contains a typo which I'll fix along with the review outcome.

**Comment by cket** [comment]
jenkins, test this please

**Comment by hannes-ucsc** [comment]
I pushed a commit which fixes the ticket ref in the commit title. IT failed due to shortage of m3.large instances. Merging anyways as previous build succeeded and newly pushed commit only changes the title.

**Pull request merged**
