### PR TITLE
Replace stats and logging process with thread (resolves #877)

### LINKED ISSUE #877: Control-C doesn't stop a Toil script run completely
When using control-c to stop a toil script, it successfully shuts down the batch system and stops execution of commands, but doesn't exit the python script and relinquish control of the command prompt to the user. The python toil script child processes are still running.

However, I can clean the jobstore using the `toil clean <jobstore_name>` on an Azure storage account. And after manually killing the python toil child processes, I can rerun another instance of toil using the same jobstore name.

### PR DESCRIPTION
**Pull request by cket**

### CODE REVIEW

**Comment by cket** [comment]
jenkins, test this please.

**Comment by cket** [comment]
jenkins, test this please.

**Comment by cket** [comment]
The first failure seems unrelated:
http://jenkins.cgcloud.info/job/toil-pull-requests/1701/testReport/junit/src.toil.test.cwl.cwlTest/CWLTest/test_run_conformance/
failure tracked in #1098

**Comment by arkal** [comment]
Looking good. Is there a reason we're dropping the worker exit code?

**Comment by cket** [comment]
@arkal if you don't see any problems I'll merge this later today or tomorrow!

**Comment by arkal** [comment]
Looked good to me.

**Pull request merged**
