### PR TITLE
partial fix for MultipleInputFeatureRequirement on workflow outputs

### PR DESCRIPTION
**Pull request by mr-c**
From https://gitter.im/bd2k-genomics-toil/Lobby?at=5a8b25cb35dd17022ec7e3c3

~~create a minimal conformance test that triggers this bug~~ Moved to https://github.com/common-workflow-language/common-workflow-language/issues/637

### CODE REVIEW

**Comment by DailyDreaming** [comment]
Probable flaky test:
- src.toil.test.provisioners.aws.awsProvisionerTest.AWSAutoscaleTestMultipleNodeTypes.testAutoScale
- http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/1991/

**Comment by mr-c** [comment]
This is ready for review & merging

**Comment by DailyDreaming** [comment]
Flaky test:
- src.toil.test.provisioners.aws.awsProvisionerTest.AWSAutoscaleTestMultipleNodeTypes.testAutoScale
- http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/1991

**Comment by DailyDreaming** [comment]
Looks good to me!

**Pull request merged**
