### PR TITLE
Handle relative paths in --workDir (resolves #1110)

### LINKED ISSUE #1110: Handle relative paths for --workDir

### PR DESCRIPTION
**Pull request by arkal**
resolves #1110

### CODE REVIEW

**Comment by arkal** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
I'm just a little apprehensive about how we are glossing over the fact that the absolute path is derived (and its existence checked) on the leader while the work directory is actually used on the workers. IIRC, the work dir doesn't even need to exist on the leader and it is created dynamically on the worker but this code enforces its existence on the leader.

**Comment by arkal** [comment]
i believe `workflowDir` is created on the worker, not `workDir` and `workDir` needs to exist on the worker. We can alternatively enforce that `workDir` begins with a leading `/` and say that only absolute paths are supported?

**Comment by hannes-ucsc** [comment]
I like that. But use os.path.isabs.

**Comment by arkal** [comment]
works for me! I'll push this asap

**Comment by arkal** [comment]
@hannes-ucsc i implemented the suggested changes. The failures seem to be unrelated to the changes.

**Comment by hannes-ucsc** [comment]
The IT failures seem to be caused by a quay.io outage.

The regular tests failure is tracked here: https://github.com/BD2KGenomics/toil/issues/1116

**Comment by arkal** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
@arkal, I apologize but I've changed my mind again because we recently changed the job store location handling to automatically convert relative paths to absolute paths. In light of this, I think we should switch back to your original approach of converting relative paths to absolute ones, on the leader.

**Comment by arkal** [comment]
@hannes-ucsc i implemented the suggested changes

**Comment by hannes-ucsc** [comment]
Will merge ASA tests pass.

**Comment by arkal** [comment]
@
Jenkins, test this please.

**Comment by cket** [comment]
jenkins, test this please

**Comment by benedictpaten** [comment]
@cket okay to merge?

**Pull request merged**
