### PR TITLE
Pass use_container to cwltool (resolves #1200)

### LINKED ISSUE #1200: Document has DockerRequirement under 'requirements' but use_container is false.
Using the most recent git [1] and a local cwltool [2], I get the following error when running a simple cwl [3]

Error:

```
(p2) [jeremiah@wireless-s1-so-150-52-240 ~]$ cwltoil ~/code/cocleaning-cwl/tools/md5sum.cwl ./ex.yml 
wireless-s1-so-150-52-240.uchicago.edu 2016-10-07 17:16:28,867 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
wireless-s1-so-150-52-240.uchicago.edu 2016-10-07 17:16:29,195 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
wireless-s1-so-150-52-240.uchicago.edu 2016-10-07 17:16:29,196 MainThread INFO toil.jobStores.fileJobStore: Path to job store directory is '/tmp/tmpNJ72E9'.
wireless-s1-so-150-52-240.uchicago.edu 2016-10-07 17:16:29,196 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: '76b2b9e5-c80a-42da-a3a3-706e3905fff3'
Traceback (most recent call last):
  File "/home/jeremiah/.virtualenvs/p2/bin/cwltoil", line 11, in <module>
    load_entry_point('toil', 'console_scripts', 'cwltoil')()
  File "/home/jeremiah/code/toil/src/toil/cwl/cwltoil.py", line 653, in main
    builder = t._init_job(job, basedir=basedir)
  File "/home/jeremiah/.virtualenvs/p2/lib/python2.7/site-packages/cwltool/process.py", line 451, in _init_job
    raise WorkflowException("Document has DockerRequirement under 'requirements' but use_container is false.  DockerRequirement must be under 'hints' or use_container must be true.")
cwltool.errors.WorkflowException: Document has DockerRequirement under 'requirements' but use_container is false.  DockerRequirement must be under 'hints' or use_container must be true.

```

[1]
https://github.com/BD2KGenomics/toil/commit/196ba62d468963d57dc36be07e382c247551af62

[2]
https://github.com/jeremiahsavage/cwltool/releases/tag/1.0_gdc_e

[3]
md5sum.cwl:

```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0

requirements:
  - class: DockerRequirement
    dockerPull: ubuntu:xenial-20160809
  - class: InlineJavascriptRequirement

class: CommandLineTool

inputs:
  - id: INPUT
    type: File
    inputBinding:
      position: 0

outputs:
  - id: OUTPUT
    type: File
    outputBinding:
      glob: $(inputs.INPUT.nameroot + ".md5")

stdout: $(inputs.INPUT.nameroot + ".md5")

baseCommand: [md5sum]
```

ex.yml:

```
INPUT:
  class: File
  location: /home/jeremiah/XX_UUID_XX.db
```

### PR DESCRIPTION
**Pull request by jeremiahsavage**
Resolves #1200

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

@jeremiahsavage, see my comments on #1200.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by cket** [comment]
@chapmanb @mr-c can you take a look at this change? Your changes in #1340 might already take care of this.

**Comment by chapmanb** [comment]
This fix is included in #1340 so we could close this and avoid needing to rebase it and get it for free as part of that PR when it's ready to merge.

**Comment by hannes-ucsc** [comment]
@chapmanb, if possible, mark a commit in #1340 as `(resolves #1200)`.

**Pull request closed without merging**
