### PR TITLE
When killing tasks, make sure to reap child processes in the process groups

### PR DESCRIPTION
**Pull request by ramyala**
Long-running tasks e.g. docker pipelines, can be abondoned on the slave nodes
when tasks are killed. Instead kill all processes belonging to the task's process
group. This requires us to make sure a new progress group is created on launching
a pipeline.

Also fixes an issue where docker containers aren't named as expected on launch.

### CODE REVIEW

**Comment by cket** [comment]
@ramyala thanks for the PR, this is great!

Jenkins, test this please.

**Comment by cket** [comment]
It looks like tests are failing with
`TypeError: <lambda>() takes exactly 1 argument (0 given)`

**Comment by ramyala** [comment]
Please review again. Fixed now.

**Comment by cket** [comment]
Jenkins, ok to test

**Comment by ramyala** [comment]
any update on this merge?

**Comment by ejacox** [comment]
Looks good. Thank you @ramyala for adding this.

**Pull request merged**
