### PR TITLE
Update cwltool version.

### PR DESCRIPTION
**Pull request by DailyDreaming**

### CODE REVIEW

**Comment by mr-c** [comment]
`src/toil/test/cwl/cwlTest.py::CWLTest::test_run_conformance FAILED`

**Comment by DailyDreaming** [comment]
Ah.  It hasn't passed the output yet, wonder what it broke.

**Comment by DailyDreaming** [comment]
```
Test [123/128] Test that expression engine does not fail to evaluate reference to self with unprovided input

Test failed: toil-cwl-runner --outdir=/mnt/ephemeral/tmp/tmpmrMSu9 --quiet v1.0/stage-unprovided-file.cwl v1.0/empty.json
Test that expression engine does not fail to evaluate reference to self with unprovided input
Returned non-zero
DEBUG:rdflib:RDFLib Version: 4.2.2
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/mnt/ephemeral/tmp/tmpQdBOlK'.
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/mnt/ephemeral/tmp/tmpQdBOlK'.
Traceback (most recent call last):
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/bin/toil-cwl-runner", line 9, in <module>
    load_entry_point('toil', 'console_scripts', 'toil-cwl-runner')()
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/cwl/cwltoil.py", line 1048, in main
    outobj = toil.start(wf1)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/common.py", line 783, in start
    return self._runMainLoop(rootJobGraph)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/common.py", line 1057, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/leader.py", line 242, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException

127 tests passed, 1 failures, 0 unsupported features
```

**Comment by DailyDreaming** [comment]
Closing this for now and waiting on larger changes.

**Pull request closed without merging**
