### PR TITLE
Conftest file for mesos batch system (resolves #307)

### LINKED ISSUE #307: "make test" breaks if Mesos isn't installed
Reported by @joelarmstrong in #296.

### PR DESCRIPTION
**Pull request by cket**

### CODE REVIEW

**Comment by cket** [comment]
Is the "1 failing check" the skipped dependencies test? Nothing actually failed.

**Comment by hannes-ucsc** [comment]
I added a check for dirty working copy. I did this to ensure that the build doesn't clobber the working copy with temporary test files. That check is failing here because, for example, the virtualenv directory is dirtying the working copy.

I fixed this on master just now, so rebasing should fix the build.

**Comment by cket** [comment]
I reran the tests here 
http://jenkins.cgcloud.info/job/toil/330/testReport/
and they passed

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Pull request merged**
