### PR TITLE
cwltoil: bring up to date with CWL v1.0 release

### PR DESCRIPTION
**Pull request by chapmanb**
Synchronizes Toil CWL support with the latest cwltool supporting v1.0 of
the CWL specification:

- Handles back compatibility of path/location specifications for files
  (path is old, location is new).
- Adjusts imports to match cwltool reorganization changes
- Some functions use kwargs instead of default arguments
  (single_job_executor, _init_job).
- Changes from output to outputSource in job outputs.

cc @tetron for sanity checks

### CODE REVIEW

**Comment by fnothaft** [comment]
+1!

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by chapmanb** [comment]
It looks like I must have broke some of the CWL tests, although can't see what specifically failed. Apologies, I'm trying to learn how to run the tests locally to see if I can fix the issues.

**Comment by hannes-ucsc** [comment]
> Apologies

No need. That's what tests are for ;-)

Note that the tests check out a specific commit of the compliance suite. I'm not surprised that they break when upgrading CWL.

**Comment by chapmanb** [comment]
Messed up rebase so closing to continue discussion in #1056

**Pull request closed without merging**
