### PR TITLE
AWS: increase default size of root volume

### PR DESCRIPTION
**Pull request by chapmanb**
CJ and all;
While testing bcbio CWL runs on AWS I'm running into the issue that bcbio Docker image is too big for the root volume size on CoreOS instances (8Gb). The failure log for this is below. This PR bumps it to 50Gb to allow for the Docker image + associated running data for a wider variety of pipelines.

Longer term it would be good if the launched nodes set this based on requested disk usage in the set of Job, which does get passed from CWL's ResourceRequirements. However I don't have enough expertise to implement that so this unblocks current attempts to test bcbio CWL runs on AWS.

```
---TOIL WORKER OUTPUT LOG---
c4382872-faad-41f4-b1ef-6045391331e0    INFO:toil:Running Toil version 3.7.0a1.dev353-00c18d033666227f86d798c6ce2f30d95f173a1e.
c4382872-faad-41f4-b1ef-6045391331e0    INFO:toil.fileStore:Starting job ('file:///home/run/test_bcbio_cwl-master/run_info-cwl-workflow/steps/prep_align_inputs.cwl' bcbio_nextgen.py runfn prep_align_inputs cwl c4382872-faad-41f4-b1ef-6045391331e0) with ID (e5ca5cd58580845cf6046cd0091b8adafdc348b8).
c4382872-faad-41f4-b1ef-6045391331e0    ['docker', 'pull', 'bcbio/bcbio']
c4382872-faad-41f4-b1ef-6045391331e0    INFO:cwltool:['docker', 'pull', 'bcbio/bcbio']
c4382872-faad-41f4-b1ef-6045391331e0    Using default tag: latest
c4382872-faad-41f4-b1ef-6045391331e0    latest: Pulling from bcbio/bcbio
c4382872-faad-41f4-b1ef-6045391331e0    8387d9ff0016: Pulling fs layer
c4382872-faad-41f4-b1ef-6045391331e0    3b52deaaf0ed: Pulling fs layer
c4382872-faad-41f4-b1ef-6045391331e0    4bd501fad6de: Pulling fs layer
c4382872-faad-41f4-b1ef-6045391331e0    a3ed95caeb02: Pulling fs layer
c4382872-faad-41f4-b1ef-6045391331e0    9537779ccc69: Pulling fs layer
c4382872-faad-41f4-b1ef-6045391331e0    a3ed95caeb02: Waiting
c4382872-faad-41f4-b1ef-6045391331e0    9537779ccc69: Waiting
c4382872-faad-41f4-b1ef-6045391331e0    4bd501fad6de: Verifying Checksum
c4382872-faad-41f4-b1ef-6045391331e0    4bd501fad6de: Download complete
c4382872-faad-41f4-b1ef-6045391331e0    3b52deaaf0ed: Verifying Checksum
c4382872-faad-41f4-b1ef-6045391331e0    3b52deaaf0ed: Download complete
c4382872-faad-41f4-b1ef-6045391331e0    a3ed95caeb02: Verifying Checksum
c4382872-faad-41f4-b1ef-6045391331e0    a3ed95caeb02: Download complete
c4382872-faad-41f4-b1ef-6045391331e0    8387d9ff0016: Verifying Checksum
c4382872-faad-41f4-b1ef-6045391331e0    8387d9ff0016: Download complete
c4382872-faad-41f4-b1ef-6045391331e0    8387d9ff0016: Pull complete
c4382872-faad-41f4-b1ef-6045391331e0    3b52deaaf0ed: Pull complete
c4382872-faad-41f4-b1ef-6045391331e0    4bd501fad6de: Pull complete
c4382872-faad-41f4-b1ef-6045391331e0    a3ed95caeb02: Pull complete
c4382872-faad-41f4-b1ef-6045391331e0    write /var/lib/docker/tmp/GetImageBlob751033652: no space left on device
```

### CODE REVIEW

**Comment by cket** [comment]
@chapmanb isn't /var/lib/docker mounted on the device's ephemeral drive rather than the root volume? We definitely don't want images to be limited to <8 GB but I think the issue here is caused by the images being written to the wrong place rather than a too small root volume.

**Comment by chapmanb** [comment]
CJ -- I'm using m4 instances which don't have ephemeral drives, I believe they just have the root volume and everything is attached there. It seems like AWS is moving away from supplying ephemeral drives in the newer instance types, which might be why the smaller instance default worked well for real runs in the past. Longer term I'd like to understand how to handle large inputs like 100Gb BAM files with respect to disk size but bumping the output should work for most smaller projects.

**Comment by cket** [comment]
I see, this is related to https://github.com/BD2KGenomics/toil/issues/1483 then. The EBS volume support is really needed for the new generation instances. We originally focused on properly handling the discovery/mounting/raiding of ephemeral drives instead of EBS support, since up until November (when we were developing autoscaling) they the old types were actually cheaper.

This might be a good stop gap, but I would also recommend using the old instance types if possible. On my end I can make EBS support of our next development sprint goals.

**Comment by chapmanb** [comment]
CJ;
General EBS support would be great. Thank you for looking at this. What do you think about this as a low-effort workaround in the short term? It would also give us a framework for eventually being able to specify and scale these longer term without dependence on the ephemeral drives. Thanks again.

**Comment by cket** [comment]
@chapmanb I'm ok with that. Did you see the CWL conformance test failure? Do you have any ideas about that?

**Comment by chapmanb** [comment]
Is it possible to retry the test run? I think this is a git clone failure when the test pulls in the CWL test repo. This PR doesn't change anything CWL related, the test repo hasn't changed in a while and I can't replicate locally so I'm hoping it's a one off problem.

**Comment by cket** [comment]
jenkins, test this please

**Comment by cket** [comment]
@chapmanb that CWL fix didn't seem to work :( I'm seeing it across all the branches now

**Comment by chapmanb** [comment]
CJ -- sorry about the issue. I've been investigating more and the issue seems to be with the recent schema-salad release. cwltool defined a `>=` requirement so it got the latest. I explicitly pinned to a working version until the CWL folks can release a new fixed version. So hopefully this will pass and can get merged and rebased into the other branches to prevent it blocking other improvements. Sorry about the issue and hope this resolves it.

**Comment by cket** [comment]
@chapmanb no worries, thanks for working on the fix!

**Comment by chapmanb** [comment]
CJ -- I think I've got this fixed but of course there was a timeout on the AWS test as soon as I got the CWL one fixed. Not sure if you need to restart this or if we can merge if the longer test passes. Fingers crossed.

**Comment by cket** [comment]
@chapmanb since the failures are unrelated I think it makes sense to merge this and fix the CWL bug since that is currently blocking other development. Thanks again!

**Pull request merged**
