### PR TITLE
Update cwltool, fix bad import (resolves #824)

### LINKED ISSUE #824: cwltool conflict version?
Hi,

I'm trying to run a CWL workflow for bcbio-nextgen in our SLURM cluster using Toil. To do so, I'm running the following command: `cwltoil --verbose --preserve-environment PATH HOME --no-container run_info-cwl-workflow/main-run_info-cwl.cwl run_info-cwl-workflow/main-run_info-cwl-samples.json`.

The command is the same than the one specified in [bcbio-nextgen docs](http://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html#running), just that I use `cwltoil` instead of `cwltool`.

When doing so, I'm getting the following error:

```
 login01 /scratch/gcarrasco/tests/test_bcbio_cwl ~> cwltoil --verbose --preserve-environment PATH HOME --no-container run_info-cwl-workflow/main-run_info-cwl.cwl run_info-cwl-workflow/main-run_info-cwl-samples.json                        Traceback (most recent call last):
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/bin/cwltoil", line 9, in <module>
    load_entry_point('toil==3.2.0a2', 'console_scripts', 'cwltoil')()
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 549, in load_entry_point
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 2542, in load_entry_point
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 2201, in load
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 2218, in require
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 835, in resolve
pkg_resources.VersionConflict: (cwltool 1.0.20160422204730 (/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/cwltool-1.0.20160422204730-py2.7.egg), Requirement.parse('cwltool==1.0.20160413143011'))
```

Looking at the code I saw that the version of `cwltool` required is set in [`setup.py`](https://github.com/BD2KGenomics/toil/blob/master/setup.py). Isn't this a too strict requirement? I'd suggest changing it for 

```
        'cwl': [
            'cwltool>=1.0]},
```

Ping @tetron :)

### PR DESCRIPTION
**Pull request by guillermo-carrasco**
Resolves #824

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
@guillermo-carrasco, thank you for the PR.

Could you please change commit message to 

`Update cwltool, fix bad import (resolves #824)`

http://chris.beams.io/posts/git-commit/

**Comment by guillermo-carrasco** [comment]
Absolutely, its done. And thank you for the good read! :)

**Comment by guillermo-carrasco** [comment]
@hannes-ucsc anything else I can do to get this merged?

Thanks!

**Comment by hannes-ucsc** [comment]
@guillermo-carrasco, I didn't catch the fact that you changed the constraint to `>=` until now, effectively pulling out the version pin. This would make Toil CI builds (and regular user installs) unstable because we would be installing whatever the latest version of cwltool is. That's clearly not what we want unless the CWL folks guarantee full backwards compatibility which I don't think they do (@tetron?).

What's your reasoning behind pulling the pin on cwltool?

**Comment by tetron** [comment]
See comment on #806

**Comment by guillermo-carrasco** [comment]
okay I understand @tetron , @hannes-ucsc . It make sense, though its quite inconvenient since it makes it harder to stay up to day with the last version of `cwltool`

**Comment by hannes-ucsc** [comment]
If CWL switched to semantic versioning we could use a sliding pin:

cwltool>=1.2.3,<1.3

CWL would have to commit to maintaining backwards compatibility among minor releases.

**Pull request closed without merging**
