### PR TITLE
Implement auto-scaling (resolves #349, resolves #600)

### LINKED ISSUE #349: Design and implement autoscaling algorithm

### LINKED ISSUE #600: Implement provisioner for EC2

### PR DESCRIPTION
**Pull request by hannes-ucsc**
Resolves #349, resolves #600.

Continues #541

### CODE REVIEW

**Comment by benedictpaten** [comment]
Is this ready to merge?! I'd like to discuss tests for this.

**Comment by hannes-ucsc** [comment]
No.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
So [changing](https://github.com/BD2KGenomics/toil-scripts/pull/251#issuecomment-214912601) the instance type to c3.large caused the Toil builds to hang in the SLURM tests. I believe this is due to the lower memory offered by c3.large compared to m3.large.

I changed the type again to c3.xlarge which has more cores and more memory than m3.large.

**Comment by hannes-ucsc** [comment]
I've added https://github.com/BD2KGenomics/cgcloud/issues/155 to track the test sensitivity to instance type.

**Comment by hannes-ucsc** [comment]
With c3.xlarge, testServiceParallelRecursive [hangs](https://github.com/BD2KGenomics/toil/issues/820).

**Comment by hannes-ucsc** [comment]
Switched back to m3.large to skip the hanging test.

Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Failed again, running out of SDB domains.

Jenkins, test this please.

**Pull request merged**
