### PR TITLE
WIP: Resource requirements tests

### PR DESCRIPTION
**Pull request by brainstorm**
Jenkins skip this please.

BOSC2017 work together with @mr-c regarding dynamic resource requirements (runtime cores/walltime/memory/disk estimation/prediction), related with issues:

https://github.com/common-workflow-language/cwltool/issues/483
https://github.com/BD2KGenomics/toil/issues/1647

- [x] Fix underlying error in `cwltool` https://github.com/common-workflow-language/cwltool/issues/483 https://github.com/common-workflow-language/cwltool/pull/488
- [ ] release new `cwltool` and integrate with toil. See also https://github.com/BD2KGenomics/toil/pull/1759

### CODE REVIEW

**Comment by ejacox** [comment]
Jenkins, add to white list

**Comment by ejacox** [comment]
Jenkins, test this please

**Comment by ejacox** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
Closing in favor of https://github.com/BD2KGenomics/toil/pull/1810 -- thanks @brainstorm !

**Pull request closed without merging**
