### PR TITLE
Merged bd2k-python-lib into Toil (resolves #1936)

### LINKED ISSUE #1936: Move bd2k-python-lib into Toil.
┆Issue Number: TOIL-7

### PR DESCRIPTION
**Pull request by ejacox**

### CODE REVIEW

**Comment by benedictpaten** [comment]
Is this stale? Still to do right? @ejacox thanks.

**Comment by ejacox** [comment]
This was part of the Python3 effort. It was put on hold in order to finish the provisioners. I believe @diekhans is now working on it, possibly in a different PR>

**Comment by diekhans** [comment]
I am poking at py3 compat, but this is a blocking matter.  Lon
has been doing some of it as part of other efforts.

Big issue is the test in doc, which would be an extreme about
of work to make py2/py3 compatible.

**Comment by DailyDreaming** [comment]
Some of this is outdated now. I'd like to see the rest pulled into toil after Azure is done but right now it's being done as other things are worked on and Azure seems like it should be the priority.

**Comment by DailyDreaming** [comment]
Closing this as bd2k-lib has been updated to be py2/3 compatible.

**Pull request closed without merging**
