### PR TITLE
More Python 3 fixes

### PR DESCRIPTION
**Pull request by adamnovak**
@DailyDreaming Here are some fixes I have done on top of your python23compat branch. I "fixed" some problems I ran into getting the tests up and running (such as the Makefile trying to always use 2.7 versions of things), and I've fixed a couple bugs that made tests fail.

I've now hit the `find_global` problem that was mentioned this morning. I can try fixing that, but I wanted to PR this first, into your python23compat pr.

### CODE REVIEW

**Comment by DailyDreaming** [comment]
I left the Makefile 2.7 requirements in purposely just for the time being, since that meant being able to merge incrementally while keeping it python2.7 consistent.  I took out the other 2.7 gatekeepers that mostly seemed redundant though.

If you're curious, using the python3 Unpickler's `find_class` method as a first naive drop in replacement:

```
        if sys.version_info[0] == 2:
            unpickler.find_global = filter_main
        else:
            unpickler.find_class = filter_main
```

Yields the error:

```
Traceback (most recent call last):
  File "/home/quokka/git/deltoil23/toil3/toil/src/toil/test/src/workerTest.py", line 58, in testNextChainableJobGraph
    self.assertEquals(jobGraph2, nextChainableJobGraph(jobGraph1, self.jobStore))
  File "/home/quokka/git/deltoil23/toil3/toil/src/toil/worker.py", line 98, in nextChainableJobGraph
    successorJob = Job._loadJob(successorJobGraph.command, jobStore)
  File "/home/quokka/git/deltoil23/toil3/toil/src/toil/job.py", line 900, in _loadJob
    return cls._unpickle(userModule, fileHandle, jobStore.config)
  File "/home/quokka/git/deltoil23/toil3/toil/src/toil/job.py", line 930, in _unpickle
    unpickler.find_class = filter_main
AttributeError: '_pickle.Unpickler' object attribute 'find_class' is read-only
```

**Comment by DailyDreaming** [comment]
Also, jenkins is down since we disabled Edwin's account on AWS. I've asked Erich to re-enable it, but expect a lot of tests to fail before that's addressed.

**Comment by adamnovak** [comment]
OK, I think I've come up with a solution for the unpickler: if monkey-patching the Python 2 method name fails, define a class and override the Python 3 method name.

Now I'm on to finding all the places we try to pickle to/from text-mode files; I've caught enough of them that I can get `src/toil/test/batchSystems/batchSystemTest.py::MaxCoresSingleMachineBatchSystemTest::testServices` to pass, which seems to exercise some of the fileStore and jobStore code.

**Comment by DailyDreaming** [comment]
Cool.  I like the unpickler solution.

**Comment by adamnovak** [comment]
It looks like we've settled on file store streams (for e.g. writeSharedFileStream) being binary-mode, so you have to encode/decode text going to/from them in Python 3. Does that make sense? Do we want to think about enhancing the API to let you specify what kind of stream you want, to make text IO easier?

**Comment by DailyDreaming** [comment]
`It looks like we've settled on file store streams (for e.g. writeSharedFileStream) being binary-mode, so you have to encode/decode text going to/from them in Python 3. Does that make sense?`

I chose binary-mode because it seemed the closest to the old python2.7 code, since the old strings were bytestrings, but I don't have any strong reason to keep it that way.  The decision was semi-arbitrary, but honestly, having not coded a lot of python 3, I am not familiar with what the typical convention there is.  If it looks odd to you having it be 'wb' and 'rb', then I am not opposed at all to going in the other direction so long as we try to be consistent.

`Do we want to think about enhancing the API to let you specify what kind of stream you want, to make text IO easier?`

If that's a use-case you have, and feel others would use, then sure.  I'm not opposed at all.  I do have a vague suspicion that that might create complications, but no concrete reason that it would.

**Comment by diekhans** [comment]
If the data can be either text or binary, then the best approach is
it to have the same parameters as open (encoding and error) and behaive
consistently.

**Comment by adamnovak** [comment]
I think we want to put off a change to the stream API until we get Python 3 actually working and passing the tests. Then we can add support for Pythonic specification of what kind of stream we want, and remove a bunch of encode/decode calls.

@DailyDreaming I'm getting to the end of the tests I can run locally that are failing. Is there a way to run e.g. the Azure job store tests outside of Jenkins?

**Comment by DailyDreaming** [comment]
@adamnovak To the first, I agree with deferring other changes until this is done.  To the second, run `make docker` and set:

TOIL_TEST_INTEGRATIVE=True;
TOIL_AZURE_KEYNAME=<yourstorageaccountname>;
TOIL_AZURE_ZONE=westus;

**Pull request closed without merging**
