### PR TITLE
GridEngine not Gridengine

### PR DESCRIPTION
**Pull request by nazamy**
There was a typo in the import statement that I corrected. Should be GridEngine not Gridengine.

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, okay to test

**Comment by ejacox** [comment]
@mr-c, do you know which Jenkins setting I need to change to give you the ability to launch tests?

**Comment by ejacox** [comment]
Jenkins, test this please.

**Comment by ejacox** [comment]
Thank you @nazamy

**Pull request merged**
