### PR TITLE
Provide better error message handling in rv() for function names

### PR DESCRIPTION
**Pull request by dgaston**
Return self.userFunctionName in rv() RuntimeError message to ease debugging of toil scripts

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Hmm, this won't work because the userFunctionName is introduced by a subclass. Given that this is a error message, I would go for a light weight approach of `getattr( self, 'userFunctionName', self.__class__.__name__ )`. Alternatively, we could introduce a `Job.name()` method that defaults to returning `self.__class__.__name__` but can be overridden by subclasses.

Also, the fact that the tests pass indicates that either all of our test jobs are functions (which I don't think is the case) or that this error condition isn't covered. IOW, we also need a test for this.

@dgaston, thank you for the contribution. Don't feel obliged to make the above changes. We will schedule them internally for the 3.2.0 release.

**Comment by dgaston** [comment]
Makes sense, happy to have helped in any way.

**Comment by hannes-ucsc** [comment]
This will be addressed by #677

**Pull request closed without merging**
