### PR TITLE
Fix service promise serialization (resolves #844)

### LINKED ISSUE #844: Promise passing to services is broken
Passing a promised return value to a service is broken, because of the way serialization happens.

### PR DESCRIPTION
**Pull request by benedictpaten**
Resolves #844

### CODE REVIEW

**Comment by fnothaft** [comment]
@benedictpaten can you squash down? For some reason this shows two commits.

**Comment by benedictpaten** [comment]
Yeah, not sure what happened.. fixing now.

**Comment by hannes-ucsc** [comment]
Commit message is wrong. Should be

```
Fix service promise serialization (resolves #844)

Adds a test in toil.test.jobServiceTest.testServiceSerialization which now passes
illustrating the issues.
```

Ideally we'd have two commits pushed independently. First commit adds test. Jenkins build fails. Second commit fixes tests. Build succeeds. @cket has this down to an art.

**Comment by hannes-ucsc** [comment]
And while you are at it, rebase on master since branch is now out of date.

**Comment by benedictpaten** [comment]
Don't understand this failure. @hannes-ucsc - is this flappy?

**Comment by benedictpaten** [comment]
I personally think this is good to go.

**Comment by hannes-ucsc** [comment]
This is the test @benedictpaten was referring to:

http://jenkins.cgcloud.info/job/toil-pull-requests/1233/testReport/junit/src.toil.test.sort.sortTest/SortTest/testAwsMesos/

**Comment by hannes-ucsc** [comment]
Tracked here: https://github.com/BD2KGenomics/toil/issues/845

**Comment by hannes-ucsc** [comment]
Continued in #846

**Pull request closed without merging**
