### PR TITLE
Add [all] extra.

### PR DESCRIPTION
**Pull request by DailyDreaming**
Allows toil to be built from source using just: `make develop extras=[all]` so that I don't have to copy-paste all of the time when building from source.  Also relocates a global variable.

### CODE REVIEW

**Comment by natanlao** [comment]
We should update the [documentation](https://toil.readthedocs.io/en/3.12.0/gettingStarted/install.html?highlight=extras#installing-toil-with-extra-features) to reflect this as well

**Comment by ejacox** [comment]
Can it be written so that the dependencies don't need to be in two places? For example, can 'all' invoke installing 'aws', 'azure', ... Having to update two lists would be a source of errors.

**Comment by DailyDreaming** [comment]
Updated docs and consolidated the list.

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Comment by DailyDreaming** [comment]
Some new flaky tests?

src.toil.test.sort.sortTest.SortTest.testAwsMesos
src.toil.test.sort.sortTest.SortTest.testGoogleSingle

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Comment by ejacox** [comment]
Thank you @DailyDreaming

**Pull request merged**
