### PR TITLE
Support remaining CWL draft-3 workflow features (resolves #712)

### LINKED ISSUE #712: Complete draft-3 feature set for cwltoil
Implement remaining cwl draft-3 features in cwltoil:

- [x] complex scatter
- [x] multiple sources to a workflow step input
- [x] valueFrom on workflow step inputs

### PR DESCRIPTION
**Pull request by tetron**
Resolves #712 

- Support complex scatter.
- Support multiple sources on workflow steps.
- Support valueFrom on workflow step input.

Passes CWL draft-3 conformance tests in local run.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by benedictpaten** [comment]
Cool, btw.

**Comment by tetron** [comment]
I don't think the test failures are related to this branch?

**Comment by hannes-ucsc** [comment]
@tetron, I think so. I will take care of this and rerun the tests.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Tests failed for unrelated reasons. Tracking that in https://github.com/BD2KGenomics/toil/issues/714.

**Pull request merged**
