### PR TITLE
add torque to the registry

### PR DESCRIPTION
**Pull request by alaindomissy**

### CODE REVIEW

**Comment by ejacox** [comment]
Jenkins add to whitelist

**Comment by ejacox** [comment]
Jenkins test this please

**Comment by ejacox** [comment]
Hey @alaindomissy, are you ready for this to merge?

**Comment by alaindomissy** [comment]
Yes please. Thanks.

**Comment by ejacox** [comment]
Thank you @alaindomissy. I imagine it was missed because it was a parallel effort.

**Pull request merged**
