### PR TITLE
Skip slow tests (resolves #1826).

### LINKED ISSUE #1826: Identify time-consuming tests.
The idea is to identify tests that can be run more quickly as a quick for code changes.

### PR DESCRIPTION
**Pull request by ejacox**
If TOIL_TEST_QUICK=True, all tests with the 'slow' decorator will be skipped. Quick, in this case, is 15 minutes on my laptop.

Any critical tests that are not too long could be added back in.

### CODE REVIEW

**Comment by joelarmstrong** [comment]
Jenkins has a list which is sortable by total runtime:

http://jenkins.cgcloud.info/job/toil-pull-requests/3098/testReport/

The fileStore tests (caching, non-caching, etc) are the longest by far, with all the jobStores a distant second.

**Comment by ejacox** [comment]
The file diff for this PR is a list of those tests marked slow. As @joelarmstrong mentioned, look at a passing Jenkins run to see timings. I used that list initially. I marked as slow anything that took longer than 25-30 seconds.

**Comment by benedictpaten** [comment]
Okay, good. I'd probably choose to keep the single machine sort tests, and all the basic single machine tests in general - as they test core toil. 

For this PR to go in, I think you need some documentation in the PR on how to run with this.

**Comment by ejacox** [comment]
jenkins, test this please

**Comment by ejacox** [comment]
Jenkins, test this please.

**Pull request merged**
