### PR TITLE
Added factory construction method for FileJobStore (resolves #834)

### LINKED ISSUE #834: Job stores are constructed inconsistently
The AWS job store has a factory method which parses a string of args and calls the __init__ method. No such method exists for File and Azure job stores, and the __init__ is directly called in common for both.

### PR DESCRIPTION
**Pull request by JakeNarkizian**
Azure's constructor will be added when #833 is merged

### CODE REVIEW

**Comment by JakeNarkizian** [comment]
@hannes-ucsc

**Comment by hannes-ucsc** [comment]
Don't you need to change the tests to use the new factory method?

If you do, can you also change "File job store" to "file job store" or "FileJobStore" in the commit message? It would be "Mesos job store" because Mesos is a proper noun, while file isn't. Otherwise, this is ok to merge.

**Comment by JakeNarkizian** [comment]
Jenkins, test this please.

**Comment by JakeNarkizian** [comment]
note to self: rename these factory methods such that the ```jobStore``` suffix is omitted.

**Comment by JakeNarkizian** [comment]
Jenkins, test this please.

**Comment by JakeNarkizian** [comment]
continued in #900

**Pull request closed without merging**
