### PR TITLE
Add --preserve-environment option (resolves #839)

### LINKED ISSUE #839: cwltoil does not pass setEnv variables to cwl job
When running cwltoil with the `--no-container` option, jobs fail if the specified CWL `baseCommand` is not found in the runtime `PATH`. This is expected, but it seems there's no way to provide that path to cwltoil. There is a `--setEnv` argument that appears to be for this purpose (setting environment variables on jobs), but cwltoil does not honor it.

Running `cwltool`, the environment (including PATH) is inherited from the parent process/shell, so binaries specified in `baseCommand` are found if they're in the `PATH`.

cwltool command: 

    PATH=$PATH:/home/dcl9/bin cwltool --no-container --outdir /home/dcl9/ggr-output/ /home/dcl9/GGR-cwl/qc/fastqc.cwl fastqc_job.json

results: [cwltool-succeed.txt](https://github.com/BD2KGenomics/toil/files/245337/cwltool-succeed.txt)

cwltoil command:

    cwltoil --jobStore /data/tmp/toil-jobstore/ --no-container --setEnv PATH=/home/dcl9/bin --outdir /home/dcl9/ggr-output/ /home/dcl9/GGR-cwl/qc/fastqc.cwl fastqc_job.json

results: [cwltoil-fail.txt](https://github.com/BD2KGenomics/toil/files/245335/cwltoil-fail.txt)

    2016-05-02 10:11:58,668 WARNING:toil.leader: P/p/jobGD9RLU:	[job 28436624] /tmp/toil-24191727-ee15-4522-93b3-6be6f484b9a6/tmpIsrHjR/localTempDir/tyO2hO6/out$ fastqc -o /var/spool/cwl --noextract --format fastq /var/lib/cwl/job378892700_tmpSLsWRh/SRC1_ab2859_GR220236_6_160309_S18.tX_repX.fastq --threads 1 --dir /tmp
    2016-05-02 10:11:58,668 WARNING:toil.leader: P/p/jobGD9RLU:	INFO:cwltool:[job 28436624] /tmp/toil-24191727-ee15-4522-93b3-6be6f484b9a6/tmpIsrHjR/localTempDir/tyO2hO6/out$ fastqc -o /var/spool/cwl --noextract --format fastq /var/lib/cwl/job378892700_tmpSLsWRh/SRC1_ab2859_GR220236_6_160309_S18.tX_repX.fastq --threads 1 --dir /tmp
    2016-05-02 10:11:58,668 WARNING:toil.leader: P/p/jobGD9RLU:	'fastqc' not found
    2016-05-02 10:11:58,669 WARNING:toil.leader: P/p/jobGD9RLU:	ERROR:cwltool:'fastqc' not found
    2016-05-02 10:11:58,669 WARNING:toil.leader: P/p/jobGD9RLU:	[job 28436624] completed permanentFail

fastqc_job.json:

    {"input_fastq_file":{ "class": "File", "path": "/data/projects/GGR/data/chip_seq/processed_raw_reads/iter-1/SRC1_ab2859_GR220236_6_160309_S18.tX_repX.fastq" }}

fastqc.cwl: https://github.com/Duke-GCB/GGR-cwl/blob/master/qc/fastqc.cwl

### PR DESCRIPTION
**Pull request by guillermo-carrasco**
This should make available the `--preserve-environment` option that is causing #839 

Ping @dleehr

### CODE REVIEW

**Comment by dleehr** [comment]
This fixed my issue in #839

**Comment by tetron** [comment]
Looks good to me

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
@guillermo-carrasco, I've invited you to our organization. That way you should have access to the Jenkins build output.

**Comment by guillermo-carrasco** [comment]
Hi @hannes-ucsc, thanks for adding me to the organization. There was indeed a syntax error that I'm not sure how it went through, but its fixed now. Yay tests!

Tests are still failing, but for something I think has nothing to do with this pull request, its failing in the JobServiceTest. Could you please have a look? Maybe I'm missing something :-/

Thanks again!

**Comment by chapmanb** [comment]
I can confirm the latest patch also works for me with local and SLURM cwltoil runs and allows use of a CWL run with a local installation rather than a Dockerized one.

**Comment by hannes-ucsc** [comment]
Unrelated test failure tracked in https://github.com/BD2KGenomics/toil/issues/908.

**Comment by guillermo-carrasco** [comment]
🎉

**Pull request merged**
