### PR TITLE
Launch workers alongside leader with toil launch-cluster (resolves #1383)

### LINKED ISSUE #1383: Add ability to provision static cluster with AWS provisioner
Right now the provisioner is only capable of autoscaling. The launch-cluster command should have options to spin up worker nodes as well. Ideally would include the addition of a grow-cluster command as well to add workers to an existing cluster

### PR DESCRIPTION
**Pull request by jessebrennan**
This allows worker nodes to be launched along side leader by adding `-w` option to `toil launch-cluster`. To spin up a cluster with 4 workers (not including the leader) run:
     `toil launch-cluster CLUSTER_NAME --nodeType=t2.micro --keyPairName foo@example.com  -w 4`

### CODE REVIEW

**Comment by jessebrennan** [comment]
Jenkins test this please

**Comment by jessebrennan** [comment]
Jenkins skip this please

**Comment by jessebrennan** [comment]
Jenkins test this please.

**Comment by cket** [comment]
Jenkins, test this please

**Pull request merged**
