### PR TITLE
Support for Slurm batchSystem (resolves #682)

### LINKED ISSUE #682: SLURM integration
Hi,

I was wondering if there is any plan to adapt a SLURM batch system into toil. I have noticed that you evaluated this a while ago in #18 and #19 , and he conclusion was that SLURM does not meet the use case for Toil, that works with scalable systems like amazon EC2.

I've seen though that you guys provide an abstraction of batch system class [here](https://github.com/BD2KGenomics/toil/blob/master/src/toil/batchSystems/abstractBatchSystem.py). And there is for example [an implementation for LSF](https://github.com/BD2KGenomics/toil/blob/master/src/toil/batchSystems/lsf.py).

Unfortunately the documentation on how to implement this class is [uncomplete](http://toil.readthedocs.org/en/latest/batchSystem.html), but having those examples should be possible to do it for SLURM.

Do you guys think its possible and see a fit for this?

Thanks a lot!

### PR DESCRIPTION
**Pull request by dleehr**
Resolves #682 

This change implements a batchSystem that talks to a slurm scheduler. It is modeled after the SGE batch system, and uses subprocess calls for `sbatch`, `sinfo`, `sacct`, and `squeue`.

So far I've only tested on simple jobs, but results are promising. I'd like to use this to run CWL workflows, but am encountering issues with cross-device linking on file staging and gathering.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Cool! What do we do about unit tests?

**Comment by dleehr** [comment]
I'll work on those, now I see there are tests for others here https://github.com/BD2KGenomics/toil/blob/master/src/toil/test/batchSystems/batchSystemTest.py

**Comment by hannes-ucsc** [comment]
Great! So ideally the tests would be run on Jenkins, our continuous integration system. For that to work we would need to install SLURM on a single node, the Jenkins slave. The setup is automated via cgcloud. Here are the steps that we have to do for GridEngine:

https://github.com/BD2KGenomics/cgcloud/blob/master/jenkins/src/cgcloud/jenkins/toil_jenkins_slave.py#L110

I'm hoping that SLURM will be easier to install than that. The base is Ubuntu 14.04.

**Comment by guillermo-carrasco** [comment]
Oh, this is great!

A pity though that I was about to submit the same PR, as mentioned in issue #682 . @dleehr your code and mine are very similar, check out [my branch](https://github.com/guillermo-carrasco/toil/blob/slurm/src/toil/batchSystems/slurm.py) if you wish :-). Since this PR is already opened, shall we stick to it? Do you need help with those tests? Otherwise I'll step aside.

Cheers!

**Comment by dleehr** [comment]
Sorry to step on your toes - I did see the discussion but didn't see a branch or a PR when I started. It looks like there's some things in both branches that should be included in the slurm support. This is my first experience with Toil, so I'd be happy to defer.

For the tests, I could definitely use some help on that. I haven't installed slurm myself, and I'm not familiar with the cgcloud system.

**Comment by guillermo-carrasco** [comment]
No problem, should've pointed to my fork in the issue before :-)

Its my first contact with Toil as well. As for SLURM, a while ago I wrote a post on how to deploy a local SLURM mini cluster using vagrant, check it out [here](http://mussol.org/2013/07/17/setting-up-a-testing-slurm-cluster/) may be useful.

I'll try to pull your branch and test it in our cluster.

**Comment by hannes-ucsc** [comment]
@guillermo-carrasco

> As for SLURM, a while ago I wrote a post on how to deploy a local SLURM mini cluster using vagrant, check it out here, may be useful.

On that page there is a reference to a Vagrantfile

> You can use this Vagrantfile from my GitHub to do so

but I can't seem to find it.

**Comment by guillermo-carrasco** [comment]
Uops, sorry. The link must have been lost when I migrated my blog. I just updated it, should be there now. In any case, find it [here](https://github.com/guillermo-carrasco/mussolblog/blob/master/setting_up_a_testing_SLURM_cluster/Vagrantfile)

Thanks for reporting!

**Comment by guillermo-carrasco** [comment]
Hi,

what's the progress of this PR? We have been testing @dleehr branch in our SLURM cluster and its working fine even with a parent Job that spawns a couple of child jobs to be run in parallel. I think that it's a very good starting point.

**Comment by dleehr** [comment]
I've been working on installing slurm on the jenkins slave. Have made some progress on the code here: https://github.com/dleehr/cgcloud/tree/jenkins-slave-slurm but have not yet deployed the machine. I plan to do that this week

**Comment by guillermo-carrasco** [comment]
Thant's great, thanks!

**Comment by hannes-ucsc** [comment]
@dleehr how are you testing your changes to cgcloud? Did you create your own jenkins-master? Do you need help testing them?

**Comment by dleehr** [comment]
@hannes-ucsc Yeah I'll be creating a jenkins-master and slave. Just need a block of uninterrupted time to keep the EC2 faucet from running :)

**Comment by dleehr** [comment]
I now have toil-jenkins-slave installing slurm:

```
$ cgcloud ssh toil-jenkins-slave
INFO: Binding to instance ... 
INFO: ... instance ready.
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-83-generic x86_64)

jenkins@ip-172-31-5-82:~$ srun ls
builds

```

I haven't looked at the test cases for other schedulers yet (to write tests for this feature), but can do that in the next week or so.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Excellent work so far, @dleehr.

Created a toil-jenkins-slave AMI using https://github.com/BD2KGenomics/cgcloud/pull/127 and running tests now but just realized that the SLURM tests aren't being run. So here is what I think is left to do:

- add a @needs_slurm decorator similar to https://github.com/BD2KGenomics/toil/blob/125b101da8bf48465494b40a03bf20308814e0fb/src/toil/test/__init__.py#L172
- add a AbstractBatchSystemTest subclass similar to https://github.com/BD2KGenomics/toil/blob/125b101da8bf48465494b40a03bf20308814e0fb/src/toil/test/batchSystems/batchSystemTest.py#L448
- resolve conflicts
- squash and rebase onto latest master (I think this should be a single commit)

**Comment by dleehr** [comment]
OK, will do. Thanks!

**Pull request closed without merging**
