### PR TITLE
Update CWL dependencies.

### PR DESCRIPTION
**Pull request by jmchilton**
xref #1757

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
Sorry @jmchilton , I thought I had the magic touch :-) We'll have to wait for @ejacox or others to bless this PR

**Comment by jessebrennan** [comment]
Let's see if I got it. Jenkins, ok to test.

**Comment by jessebrennan** [comment]
Jenkins test this please

**Comment by ejacox** [comment]
Jenkins test this please.

**Comment by ejacox** [comment]
@mr-c and @jessebrennan, you don't have the Jenkin's magic touch. However, you should be able to do a trivial edit (i.e. add a space) and commit using Github, which would trigger a build.

**Comment by mr-c** [comment]
@jmchilton 
```
--- Running conformance test v1.0 on /mnt/ephemeral/workspace/toil-pull-requests/venv/bin/cwltoil ---
Traceback (most recent call last):
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/bin/cwltoil", line 9, in <module>
    load_entry_point('toil', 'console_scripts', 'cwltoil')()
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (typing 3.6.1 (/mnt/ephemeral/workspace/toil-pull-requests/venv/lib/python2.7/site-packages), Requirement.parse('typing<3.6,>=3.5.2'), set(['cwltest']))
Test [1/87] 
```

**Comment by mr-c** [comment]
also failed was `src.toil.test.cwl.cwlTest.CWLTest.test_run_revsort`
```
Traceback (most recent call last):
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/test/cwl/cwlTest.py", line 57, in test_run_revsort
    u'checksum': u'sha1$b9214658cc453331b62c2282b772a5c063dbd284'}})
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/test/cwl/cwlTest.py", line 43, in _tester
    self.assertEquals(out, expect)
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 835, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: {u'output': {u'checksum': u'sha1$b9214658cc453331b62c2282b772a5c063dbd284', u'ba [truncated]... != {u'output': {u'path': u'/mnt/ephemeral/tmp/toil-test-toil.test.cwl.cwlTest.CWLTe [truncated]...
  {u'output': {u'basename': u'output.txt',
               u'checksum': u'sha1$b9214658cc453331b62c2282b772a5c063dbd284',
               u'class': u'File',
-              u'http://commonwl.org/cwltool#generation': 0,
-              u'nameext': u'.txt',
-              u'nameroot': u'output',
               u'path': u'/mnt/ephemeral/tmp/toil-test-toil.test.cwl.cwlTest.CWLTest-test_run_revsort-c6JptQ/output.txt',
               u'size': 1111}}
```

**Comment by ejacox** [comment]
Jenkins add to whitelist

**Comment by mr-c** [comment]
@jmchilton I think I fixed the version conflicts

**Comment by mr-c** [comment]
@jmchilton 
```
Test [82/87] 

Test failed: /mnt/ephemeral/workspace/toil-pull-requests/venv/bin/cwltoil --outdir=/mnt/ephemeral/tmp/tmpTfhYbX --quiet v1.0/count-lines10-wf.cwl v1.0/wc-job.json
Test embedded subworkflow
Returned non-zero
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/fileStore.py", line 1468, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/fileStore.py", line 1468, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting


Exception RuntimeError: RuntimeError('cannot join current thread',) in <bound method CachingFileStore.__del__ of <toil.fileStore.CachingFileStore object at 0x2b7e1fbaa4d0>> ignored
Traceback (most recent call last):
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/bin/cwltoil", line 9, in <module>
    load_entry_point('toil', 'console_scripts', 'cwltoil')()
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/cwl/cwltoil.py", line 768, in main
    outobj = toil.start(wf1)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/common.py", line 711, in start
    return self._runMainLoop(rootJobGraph)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/common.py", line 969, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/leader.py", line 201, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException: The job store 'file:/mnt/ephemeral/tmp/tmpRr82iI' contains 1 failed jobs: 'file:///mnt/ephemeral/workspace/toil-pull-requests/src/toil/test/cwl/spec/v1.0/v1.0/parseInt-tool.cwl' X/M/jobUl0dQN
=========> Failed job 'file:///mnt/ephemeral/workspace/toil-pull-requests/src/toil/test/cwl/spec/v1.0/v1.0/parseInt-tool.cwl' X/M/jobUl0dQN 
---TOIL WORKER OUTPUT LOG---
[job wc-tool.cwl] /mnt/ephemeral/tmp/tmp7YpLMR$ wc < /mnt/ephemeral/tmp/tmp3eB3vr/stgc35465b3-5467-47c6-a22f-283a55696469/whale.txt > /mnt/ephemeral/tmp/tmp7YpLMR/output
INFO:cwltool:[job wc-tool.cwl] /mnt/ephemeral/tmp/tmp7YpLMR$ wc < /mnt/ephemeral/tmp/tmp3eB3vr/stgc35465b3-5467-47c6-a22f-283a55696469/whale.txt > /mnt/ephemeral/tmp/tmp7YpLMR/output
[job wc-tool.cwl] completed success
INFO:cwltool:[job wc-tool.cwl] completed success
Failed to evaluate expression:
Expression evaluation error:
("Syntax error in parameter reference '%s' or used Javascript code without specifying InlineJavascriptRequirement.", "({'output': parseInt(inputs.file1.contents)})")
WARNING:cwltool:Failed to evaluate expression:
Expression evaluation error:
("Syntax error in parameter reference '%s' or used Javascript code without specifying InlineJavascriptRequirement.", "({'output': parseInt(inputs.file1.contents)})")
Traceback (most recent call last):
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/worker.py", line 340, in main
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/job.py", line 1289, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/job.py", line 1234, in _run
    return self.run(fileStore)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/cwl/cwltoil.py", line 309, in run
    raise cwltool.errors.WorkflowException(status)
WorkflowException: permanentFail
ERROR:toil.worker:Exiting the worker because of a failed job on host ip-172-31-30-155
<=========
```

**Comment by mr-c** [comment]
@jmchilton run the test with
`python2.7 -m pytest -vvv src/toil/test/cwl/cwlTest.py::CWLTest`

or

`make test tests=src/toil/test/cwl/cwlTest.py::CWLTest`

**Comment by benedictpaten** [comment]
Is this now out of day, given Peter's pr on cell?

**Comment by benedictpaten** [comment]
Grr, autocorrect error, meant cwl not cell.

**Comment by mr-c** [comment]
Yep, good catch.

**Pull request closed without merging**
