### PR TITLE
Azure jobStore now retries on the same exceptions Boto does (resolves #341)

### LINKED ISSUE #341: Azure job store should retry operations
From http://jenkins.cgcloud.info/job/toil/367/testReport/junit/src.toil.test.jobStores.jobStoreTest/AzureJobStoreTest/testFileDeletion/

```
Error Message

timeout: timed out
Stacktrace

self = <toil.test.jobStores.jobStoreTest.AzureJobStoreTest testMethod=testFileDeletion>

    def testFileDeletion(self):
        """
                Intended to cover the batch deletion of items in the AWSJobStore, but it doesn't hurt running it on the
                other job stores.
                """
        job = self.master.create("1", 2, 3, 4, 0)
        file_list = []
        # FIXME: tie 30 to batch limit in AWSJobStore
        for file in xrange(0, 30):
            file_list.append(self.master.getEmptyFileStoreID(job.jobStoreID))
>       self.master.delete(job.jobStoreID)

src/toil/test/jobStores/jobStoreTest.py:271: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/toil/jobStores/azureJobStore.py:147: in delete
    self.deleteFile(jobStoreFileID)
src/toil/jobStores/azureJobStore.py:179: in deleteFile
    self._dissociateJobWithFile(jobStoreFileID)
src/toil/jobStores/azureJobStore.py:293: in _dissociateJobWithFile
    self.jobFileIDs.delete_entity(partition_key=jobStoreID, row_key=jobStoreFileID)
src/toil/jobStores/azureJobStore.py:445: in callable
    return function(**kwargs)
venv/local/lib/python2.7/site-packages/azure/storage/tableservice.py:562: in delete_entity
    self._perform_request(request)
venv/local/lib/python2.7/site-packages/azure/storage/storageclient.py:172: in _perform_request
    resp = self._filter(request)
venv/local/lib/python2.7/site-packages/azure/storage/tableservice.py:644: in _perform_request_worker
    return self._httpclient.perform_request(request)
venv/local/lib/python2.7/site-packages/azure/http/httpclient.py:218: in perform_request
    self.send_request_headers(connection, request.headers)
venv/local/lib/python2.7/site-packages/azure/http/httpclient.py:197: in send_request_headers
    connection.endheaders()
/usr/lib/python2.7/httplib.py:975: in endheaders
    self._send_output(message_body)
/usr/lib/python2.7/httplib.py:835: in _send_output
    self.send(msg)
/usr/lib/python2.7/httplib.py:797: in send
    self.connect()
/usr/lib/python2.7/httplib.py:1178: in connect
    self.timeout, self.source_address)
```

### PR DESCRIPTION
**Pull request by joelarmstrong**
We now retry Azure ops 5 times on timeout and other TCP socket errors (as does Boto). HTTP error codes are handled by the Azure API, so they aren't retried.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
How do we go about testing this?

**Comment by hannes-ucsc** [comment]
In the AWS job store, the retry code gets exercised all the time due to the eventual consistency. In Azure these exceptions happen much less frequently. I like how you simplified the context-manager and generator combo to not be stateful but I have my doubts that it works when a retry is successful.

**Comment by joelarmstrong** [comment]
I think that setting up proper automated testing for this is probably out of the question, but I just set up [Vaurien](https://vaurien.readthedocs.org/en/1.8/) on my local machine to test it out. The retries seem to work out fine, on timeout and on other weird connection issues.

I did add another class of HTTP exceptions to the retriable exception list, though, because if the HTTP response is incomplete (bad status line, etc), httplib raises its own exceptions.

I could put in a doctest like `retry_sdb`'s, showing that at least that piece works?

**Comment by hannes-ucsc** [comment]
Yes, doctests would be great.

Just glancing at the code I am surprised how this is not always doing everything num_retries times, successful or not? How is the retry loop stopped if the request succeeded?

**Comment by joelarmstrong** [comment]
... whoops. You're totally right. Will fix and add doctests.

**Comment by hannes-ucsc** [comment]
Once this is done, I will probably ask to have all commits squashed. You might want to do this right away when you think its ready to avoid another round-trip.

**Comment by joelarmstrong** [comment]
OK, it's ready now, thanks.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Pull request merged**
