### PR TITLE
Issues/738 running on azure

### LINKED ISSUE #738: Running on Azure
docs/running 'Running on Azure'

### PR DESCRIPTION
**Pull request by adamnovak**
This should close #738, assuming my understanding of `toil clean` is correct.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
> This should close #738

Then one of the commits should reference that ticket number in its message. Also, you'll probably want to squash this down into one commit.

**Comment by adamnovak** [comment]
How about now?

**Comment by hannes-ucsc** [comment]
I'd rather have the ticket reference in the first line.

**Comment by jvivian** [comment]
Awesome @adamnovak , thanks a lot for this.

**Pull request merged**
