### PR TITLE
Fix flaky tests by lowering sort.py memory requirements.

### PR DESCRIPTION
**Pull request by DailyDreaming**
Changes the amount of memory that the sort example requires. I want to see if this fixes our flaky tests in the short term (though resource allocation in the long term should be reworked because this seems like a symptom of a different problem).

### CODE REVIEW

**Comment by DailyDreaming** [comment]
It passed the previously failing autoscale tests, but we have a new failing google test?
- src.toil.test.sort.sortTest.SortTest.testGoogleMesos
- http://jenkins.cgcloud.info/job/toil-pull-requests/3746

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Comment by DailyDreaming** [comment]
Google failures:
- src.toil.test.sort.sortTest.SortTest.testGoogleMesos
- http://jenkins.cgcloud.info/job/toil-pull-requests/3748
- src.toil.test.jobStores.jobStoreTest.GoogleJobStoreTest.test_testImportExportFile__otherCls_googlejobstoretest__size_partsize
- http://jenkins.cgcloud.info/job/toil-pull-requests/3748

**Comment by ejacox** [comment]
Jenkins, test this please.

**Comment by DailyDreaming** [comment]
Google failures:
- src.toil.test.provisioners.gceProvisionerTest.GCEAutoscaleTest.testSpotAutoScale
- http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/2050

**Pull request merged**
