### PR TITLE
PBSPro support

### PR DESCRIPTION
**Pull request by brainstorm**
The commercial version of PBS only seems to support JSON output.
The oss version, only does XML.

This PR takes into account this quirk and tries to accomodate for different versions (privative and open).

Thanks @cjfields and @ohofmann for your support.

@cjfields Could you please try this version/commit in your NCSA system just in case I broke something?

@toil_mantainers, the `--disableCache` option is problematic, I would love advice on how to handle it: https://github.com/BD2KGenomics/toil/compare/master...brainstorm:pbspro?expand=1#diff-ec7c0fff4aad88175b4920cd3d1e5f8fR824

I'm aware it has been an issue in the past and @chapmanb managed to address it in PR https://github.com/BD2KGenomics/toil/pull/1090, but I'm not able to let the code below uncommented.

### CODE REVIEW

**Comment by brainstorm** [comment]
A small issue that might need optimization with the current PR as-is:

```
$ time pbsnodes -a -F json
(...)
real    0m38.513s 
user    0m0.568s
sys     0m0.213s
```

Enumerating nodes with pbsnodes can substantially increase job submission/preparing time. Probably one could subset the query above to speed up job submission or perhaps stream/schedule the JSON somehow into Toil? Feedback welcome!

**Comment by cjfields** [comment]
@brainstorm sure, I'll set up a test run.

**Comment by cket** [comment]
Thanks for the PR! Jenkins, test this please

**Comment by brainstorm** [comment]
I don't have access to the Jenkins instance above, but apparently several tests failed... mostly due to the `disableCache` commented code. May I get some suggestions on how to fix that?

On another note, other reviewers of this PR (NCI folks in Australia), pointed out that enumerating nodes is a costly operation that can be killed right away from this class and even from the top abstract class, since neither `maxCPU` nor `maxMEM` are actually used in Toil (thanks @chapmanb and @ohofmann for pointing that out):

https://github.com/BD2KGenomics/toil/blob/master/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L287

What are your thoughts on that @cket? Can we just kill those calculations from the schedulers and the base abstract class? That could save quite a bit of time/resources when submitting jobs!

**Comment by ohofmann** [comment]
For context: this is the system were we'll mostly be using Toil, i.e., the target of all of @chapmanb 's current bcbio/CWL efforts. Any and all help very much appreciated.

**Comment by cjfields** [comment]
@brainstorm @ohofmann I haven't run the entire test suite but the Torque-specific tests passed for me:

```
make test tests=src/toil/test/batchSystems/batchSystemTest.py::TorqueBatchSystemTest
which: no docker in (/home/a-m/cjfields/brainstorm/venv/bin:/home/apps/libxslt/libxslt-1.1.28/bin:/home/apps/libxml2/libxml2-2.9.1/bin:/home/apps/OpenBLAS/OpenBLAS-0.2.19/bin:/home/apps/python/python-2.7.9/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/eclipse:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/usr/local/maui/bin:/opt/torque/bin:/opt/torque/sbin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/dell/srvadmin/bin:/home/a-m/cjfields/bin:/home/a-m/cjfields/python/python2.7.9/bin)
Makefile:93: Cannot find 'docker' executable. Docker-related targets will be skipped.
Skipping 'docker' target as TOIL_DOCKER_REGISTRY is empty or Docker is not installed.
TOIL_APPLIANCE_SELF=/:3.7.0a1-f60387f5d2be4cd192f1b9ba17d8b080595df55a \
	    python2.7 -m pytest -vv src/toil/test/batchSystems/batchSystemTest.py::TorqueBatchSystemTest
======================================================================================= test session starts ========================================================================================
platform linux2 -- Python 2.7.9, pytest-2.8.3, py-1.4.33, pluggy-0.3.1 -- /home/a-m/cjfields/brainstorm/venv/bin/python2.7
cachedir: .cache
rootdir: /home/a-m/cjfields/brainstorm, inifile: setup.cfg
collected 7 items

src/toil/test/batchSystems/batchSystemTest.py::TorqueBatchSystemTest::testAvailableCores PASSED
src/toil/test/batchSystems/batchSystemTest.py::TorqueBatchSystemTest::testCheckResourceRequest PASSED
src/toil/test/batchSystems/batchSystemTest.py::TorqueBatchSystemTest::testGetRescueJobFrequency PASSED
src/toil/test/batchSystems/batchSystemTest.py::TorqueBatchSystemTest::testResultFile PASSED
src/toil/test/batchSystems/batchSystemTest.py::TorqueBatchSystemTest::testRunJobs PASSED
src/toil/test/batchSystems/batchSystemTest.py::TorqueBatchSystemTest::testScalableBatchSystem PASSED
src/toil/test/batchSystems/batchSystemTest.py::TorqueBatchSystemTest::testSetEnv PASSED

==================================================================================== 7 passed in 102.43 seconds ====================================================================================
```

**Comment by cket** [comment]
Jenkins, test this please. I believe many of the failing tests were due to problems with our jenkins server rather the PR. 

I'm ok with not implementing `obtainSystemConstants` for this batch system. I think it's meant to be used to warn the user when the values of `maxCores` & `maxMemory` are greater than the system's resources, which is nice but isn't behavior specified by the batch system interface. Plus, as you pointed out, it isn't used anyway. 

Can you clarify what is wrong with `disableCaching`? Caching is enabled by default but not all systems support it, so the the check that you commented out is meant to ensure that the user isn't trying to use caching on those systems.

**Comment by brainstorm** [comment]
@cket This is what happens when I uncomment the disableCaching code I commented previously on `common.py`:

```
-bash-4.1$ toil clean toilWorkflowRun && python toil_sample_job.py
raijin5 2017-04-19 01:08:39,946 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
raijin5 2017-04-19 01:08:39,946 MainThread INFO toil.utils.toilClean: Attempting to delete the job store
raijin5 2017-04-19 01:08:39,989 MainThread INFO toil.utils.toilClean: Successfully deleted the job store
raijin5 2017-04-19 01:08:40,435 MainThread INFO toil.lib.bioio: Root logger is at level 'DEBUG','toil' logger at level 'DEBUG'.
raijin5 2017-04-19 01:08:40,436 MainThread INFO toil.lib.bioio: Root logger is at level 'DEBUG','toil' logger at level 'DEBUG'.
raijin5 2017-04-19 01:08:40,439 MainThread DEBUG toil.jobStores.fileJobStore: Path to job store directory is '/home/005/rg3930/tmp/toilWorkflowRun'.
raijin5 2017-04-19 01:08:40,440 MainThread INFO toil.jobStores.abstractJobStore: The workflow IDis: 'd75f9f0c-5134-4d71-a911-7489427bc5ea'
Traceback (most recent call last):
  File "toil_sample_job.py", line 31, in <module>
    Job.Runner.startToil(parent, options)
  File "/home/005/rg3930/dev/toil/src/toil/job.py", line 740, in startToil
    return toil.start(job)
  File "/home/005/rg3930/dev/toil/src/toil/common.py", line 661, in start
    self._batchSystem = self.createBatchSystem(self.config)
  File "/home/005/rg3930/dev/toil/src/toil/common.py", line 827, in createBatchSystem
    'use this batch system.' % config.batchSystem)
RuntimeError: torque currently does not support shared caching.  Set the --disableCaching flag if you want to use this batch system.
```

**Comment by cket** [comment]
@brainstorm yes, caching is enabled by default & it looks like torque doesn't support caching. What happens when you pass `--disableCaching`? 

Also, just a heads up - every time a commit is pushed it will trigger a Jenkins build. If you don't need jenkins to test every commit you can push multiple commits at once, that way only the most recent commit will be tested. 

Jenkins, ok to test.

**Comment by brainstorm** [comment]
@cket, right on, I was passing the `--disableCaching` in the wrong place. Just set it as `options.disableCaching = True` in my script and all went fine. I would say this is safe to merge as it is.

Sorry for the extra CI triggering with my commits, just thought it had to be tested now with my final changes and that the discussion about `obtainConstraints` should be in the commits/pullrequest history too... is there an equivalent for TravisCI's `[ci-skip]` in your Jenkins installation?

I'll review the docs to reflect my changes, but other than that, it should be safe to merge.

**Comment by cket** [comment]
@brainstorm no worries, you didn't trigger anything unnecessarily. I was just letting you know since Jenkins' behavior changes after the 'ok to test' directive (vs. the 'test this please' directive). We don't have anything set up that is equivalent to `ci-skip` but you can toggle building for the whole PR via adding or removing 'Jenkins, skip this please' to the PR's description.

**Comment by cjfields** [comment]
\o/

**Comment by brainstorm** [comment]
@cket When are we having a new Toil github release? Would be great to see this PR and other improvements packaged and pushed to bioconda :)

**Pull request merged**
