### PR TITLE
Added various combinations of job stores and batch systems to the sort test (resolves #377)

### LINKED ISSUE #377: Add sortTest for GridEngine and Parasol

### PR DESCRIPTION
**Pull request by hannes-ucsc**

### CODE REVIEW

**Comment by joelarmstrong** [comment]
Doh! I wonder if this is an error, (#381?) or just the azure code being slow as hell.

**Comment by joelarmstrong** [comment]
#386 should fix this, sorry about that!

**Comment by hannes-ucsc** [comment]
I found an easy way to accelerate GridEngine scheduling (by default it looks at the queue every 15s). Hopefully that will make the GridEngine tests faster.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Pull request merged**
