### PR TITLE
CWL: avoid early removal of the temporary outdir

### PR DESCRIPTION
**Pull request by chapmanb**
A recent change in 3.10.1 (https://github.com/BD2KGenomics/toil/commit/a909bada25940803f3dc9351fb8b6cd72e3769f0)
caused temporary output directories to get removed prior to finalizing a
Toil step, resulting in missing file errors when the outputs reference
files in the temporary directory. This fixes the issue by putting
them in the defined tempdir. cc @tetron for review.

### CODE REVIEW

**Comment by mr-c** [comment]
Can we get a new test case?

**Comment by tetron** [comment]
This might explain why bcbio and biowardrobe are broken @DailyDreaming @ejacox

**Comment by chapmanb** [comment]
Peter -- that's exactly right. The errors you get out are a bit confusing since the job completes but then during Toil processing it complains about missing files that were in this directory. Thanks much for looking at this.

Michael -- I don't have a minimal test case but it causes this bcbio test case to fail: https://github.com/bcbio/test_bcbio_cwl/tree/master/somatic

**Comment by Irrationone** [comment]
`temp_output_dir`'s (`out_tmpdir*`) seem to be sticking around after CWL step completion (with toil-cwl-runner), which is causing worker node disks to fill when running on Azure in the cloud (eventually resulting in out of space errors, since each step creates a ~500MB output file). I presume it has something to do with this pull request -- could they be deleted earlier? Thanks!

**Comment by mr-c** [comment]
@Irrationone Can you make a separate issue for that? A comment on a closed PR is likely to get lost 🙂

**Pull request merged**
