### PR TITLE
Test serially by default (fixes #1284)

### LINKED ISSUE #1284: Tests should be run serially by default

### PR DESCRIPTION
**Pull request by natanlao**
Rename target 'test-serially' to 'test' and 'test' to 'test-parallel'

### CODE REVIEW

**Comment by natanlao** [comment]
@hannes-ucsc

**Comment by hannes-ucsc** [comment]
Regular build failed as expected because no test report was created. But all the tests all passed.

It is unclear to me as to why the IT failed. Tracking this in https://github.com/BD2KGenomics/toil/issues/1334.

**Comment by hannes-ucsc** [comment]
Will change Jenkins config now and then merge.

**Comment by natanlao** [comment]
@hannes-ucsc

**Comment by hannes-ucsc** [comment]
@natanlao, https://github.com/BD2KGenomics/toil/pull/1330/commits/f240877890b1c3b8600e6f10e900e4dcb07a6b31 commit message needs to be more informative.

The IT failures are very odd.

Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
> @natanlao, https://github.com/BD2KGenomics/toil/pull/1330/commits/f240877890b1c3b8600e6f10e900e4dcb07a6b31 commit message needs to be more informative.

Scratch that as I will squash in the end. Otherwise (i.e. for a permanent commit) the message would have been too cryptic.

**Comment by hannes-ucsc** [comment]
Note to self: remember to merge together with #1336.

**Pull request merged**
