### PR TITLE
Remove out of date doc comment (connected to #547)

### PR DESCRIPTION
**Pull request by hannes-ucsc**
Continued from #847

### CODE REVIEW

**Comment by jtratner** [comment]
Just so I understand for future contributions - is there a reason why the prior PR was closed and reopened within the repo? Limitation of Jenkins?

Anything else I should do for structuring contributions going forward?

**Comment by hannes-ucsc** [comment]
@jtratner Oops, yes, I should have explained. I wanted the ticket reference in the commit title. That's all I changed. Thank you for spotting this and for the PR!

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
The previous build failed on an Azure inconsistency issue which I don't feel like tracking because I hope #833 fixes it.

**Comment by benedictpaten** [comment]
@hannes-ucsc We should write a contributing section to the docs. I'll make an issue and assign to you.

**Comment by hannes-ucsc** [comment]
Another spurious failure. Tracked as #853.

Jenkins, test this please.

**Pull request merged**
